/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import InterfazGrafica.Busqueda.BuscarAnalisisLaboratorio;
import InterfazGrafica.Busqueda.BuscarCriterioAnalisisLaboratorio;
import InterfazGrafica.Busqueda.BuscarLote;
import InterfazGrafica.Busqueda.BuscarGenerico;
import InterfazGrafica.Busqueda.BuscarEquipamiento;
import InterfazGrafica.Busqueda.BuscarOrdenCompra;
import LogicaDeNegocio.AnalisisLaboratorio;
import LogicaDeNegocio.CriterioAnalisisLaboratorio;
import LogicaDeNegocio.Equipamiento;
import LogicaDeNegocio.ExcepcionCargaParametros;
import LogicaDeNegocio.Lote;
import LogicaDeNegocio.OrdenDeCompra;
import LogicaDeNegocio.Organizacion;
import LogicaDeNegocio.Proveedor;
import Persistencia.ExcepcionPersistencia;
import java.awt.Component;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author usuario
 */
public class GestionAnalisisLaboratorio extends javax.swing.JFrame implements TransferenciaInstancias {
    
    /**
     * Creates new form ABMProveedor
     */
    private Organizacion organizacion;
    private JFrame ventanaAnterior;
    private AnalisisLaboratorio unObjetoSeleccionado;
    private String trayectoriaActual;
    private String operacionActual;
    
    private final String textoAlta = "Registrar un análisis";
    private final String textoBaja = "Anular un análisis";
    private final String textoModificacion = "Modificar un análisis";
    
    private Lote unLote;
    private Equipamiento unEquipamiento;
    private CriterioAnalisisLaboratorio unCriterioSeleccionado;
    private OrdenDeCompra unaOrdenDeCompra;
    
    public void setUnObjetoSeleccionado(AnalisisLaboratorio unObjetoSeleccionado) {
        this.unObjetoSeleccionado = unObjetoSeleccionado;
    }
    public GestionAnalisisLaboratorio() {
        initComponents();
    }



    public GestionAnalisisLaboratorio(Organizacion organizacion, JFrame ventanaAnterior, String trayectoriaAnterior) {
        this.setUndecorated(true);
        initComponents();
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.organizacion = organizacion;
        this.getContentPane().setBackground(ParametrosDeInterfaz.colorFondo);
        setIconImage(new ImageIcon(getClass().getResource(ParametrosDeInterfaz.rutaIcono)).getImage());
        
        trayectoriaActual = trayectoriaAnterior+" - Gestión de análisis";
        cabeceraDeVentana.configurarCabecera(ventanaAnterior, this, "Gestión de análisis", this.trayectoriaActual, organizacion.getUsuarioActivo().getApellido()+", "+organizacion.getUsuarioActivo().getNombre());
        
        

        this.setVisible(true); 
        jBBuscar.setVisible(false);
        
        
        this.ventanaAnterior = ventanaAnterior;
        habilitarCamposIniciales();
        ParametrosDeInterfaz.configurarVentana(this);
    }
    private void organizarElementos(){
        this.deshabilitarTodo();
        switch((String)jCBOperacion.getSelectedItem()){
            case "Registrar":
                prepararAlta();
                break;
            case "Anular":
                prepararBaja();
                break;
            case "Modificar":
                prepararModificacion();
                break;
            default:
                limpiarCampos();
                break;
                
        }
        //this.pack();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jBConcretarAccion = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jCBOperacion = new javax.swing.JComboBox<>();
        jBBuscar = new javax.swing.JButton();
        cabeceraDeVentana = new InterfazGrafica.CabeceraDeVentana();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLStaticCampo3 = new javax.swing.JLabel();
        jLStaticCampo4 = new javax.swing.JLabel();
        jLStaticCalendar1 = new javax.swing.JLabel();
        jC1 = new com.toedter.calendar.JDateChooser();
        jLStaticCampo5 = new javax.swing.JLabel();
        jLOperacionSeleccionada = new javax.swing.JLabel();
        jLStaticEtiqueta2 = new javax.swing.JLabel();
        jLStaticEtiqueta1 = new javax.swing.JLabel();
        jLStaticCampo1 = new javax.swing.JLabel();
        jLStaticEtiqueta3 = new javax.swing.JLabel();
        jLStaticEtiqueta8 = new javax.swing.JLabel();
        jLStaticEtiqueta9 = new javax.swing.JLabel();
        jLStaticEtiqueta7 = new javax.swing.JLabel();
        jLStaticEtiqueta10 = new javax.swing.JLabel();
        jLStaticCampo2 = new javax.swing.JLabel();
        jBBuscarLaboratorio = new javax.swing.JButton();
        NumberFormat formateadorCampoFloat = NumberFormat.getInstance();
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo1 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo2 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo3 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo4 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo5 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        jLStaticEtiqueta11 = new javax.swing.JLabel();
        jLStaticEtiqueta12 = new javax.swing.JLabel();
        jBBuscarCriterio = new javax.swing.JButton();
        jLStaticEtiqueta13 = new javax.swing.JLabel();
        jLStaticEtiqueta14 = new javax.swing.JLabel();
        jLStaticCampo6 = new javax.swing.JLabel();
        jLStaticCampo7 = new javax.swing.JLabel();
        jLStaticCampo8 = new javax.swing.JLabel();
        jLStaticCampo9 = new javax.swing.JLabel();
        jLStaticCampo10 = new javax.swing.JLabel();
        jCB1 = new javax.swing.JComboBox<>();
        jCB2 = new javax.swing.JComboBox<>();
        jCB3 = new javax.swing.JComboBox<>();
        jCB4 = new javax.swing.JComboBox<>();
        jLStaticCampo11 = new javax.swing.JLabel();
        jCB5 = new javax.swing.JComboBox<>();
        jCB6 = new javax.swing.JComboBox<>();
        jLStaticCampo12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLStaticEtiqueta6 = new javax.swing.JLabel();
        jBBuscarLote = new javax.swing.JButton();
        jLStaticEtiqueta4 = new javax.swing.JLabel();
        jLStaticEtiqueta5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLStaticEtiqueta15 = new javax.swing.JLabel();
        jLStaticEtiqueta16 = new javax.swing.JLabel();
        jBBuscarOrdenDeCompra = new javax.swing.JButton();
        jLStaticEtiqueta17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jBConcretarAccion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBConcretarAccion.setText("Aceptar");
        jBConcretarAccion.setEnabled(false);
        jBConcretarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConcretarAccionActionPerformed(evt);
            }
        });

        jBCancelar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setText("Seleccione una operacion");

        jCBOperacion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Registrar", "Modificar", "Anular" }));
        jCBOperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBOperacionItemStateChanged(evt);
            }
        });

        jBBuscar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscar.setText("Buscar un Analisis de Laboratorio");
        jBBuscar.setEnabled(false);
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLStaticCampo3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo3.setText("Porcentaje de polvo");
        jLStaticCampo3.setEnabled(false);

        jLStaticCampo4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo4.setText("Porcentaje de hoja");
        jLStaticCampo4.setEnabled(false);

        jLStaticCalendar1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCalendar1.setText("Fecha de origen");
        jLStaticCalendar1.setEnabled(false);

        jC1.setEnabled(false);
        jC1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCampo5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo5.setText("Porcentaje de humedad");
        jLStaticCampo5.setEnabled(false);

        jLOperacionSeleccionada.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLOperacionSeleccionada.setText("Operación sobre un Concepto");
        jLOperacionSeleccionada.setEnabled(false);

        jLStaticEtiqueta2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta2.setText("Laboratorio seleccionado");
        jLStaticEtiqueta2.setEnabled(false);

        jLStaticEtiqueta1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta1.setText("Laboratorio asociado");
        jLStaticEtiqueta1.setEnabled(false);

        jLStaticCampo1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo1.setText("Porcentaje de semilla");
        jLStaticCampo1.setEnabled(false);

        jLStaticEtiqueta3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta3.setText("Etiqueta 3");
        jLStaticEtiqueta3.setEnabled(false);

        jLStaticEtiqueta8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta8.setText("%");
        jLStaticEtiqueta8.setEnabled(false);

        jLStaticEtiqueta9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta9.setText("%");
        jLStaticEtiqueta9.setEnabled(false);

        jLStaticEtiqueta7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta7.setText("%");
        jLStaticEtiqueta7.setEnabled(false);

        jLStaticEtiqueta10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta10.setText("%");
        jLStaticEtiqueta10.setEnabled(false);

        jLStaticCampo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo2.setText("Porcentaje de palo");
        jLStaticCampo2.setEnabled(false);

        jBBuscarLaboratorio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscarLaboratorio.setText("Buscar un laboratorio");
        jBBuscarLaboratorio.setEnabled(false);
        jBBuscarLaboratorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarLaboratorioActionPerformed(evt);
            }
        });

        jTFCampo1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta11.setText("%");
        jLStaticEtiqueta11.setEnabled(false);

        jLStaticEtiqueta12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta12.setText("Criterio de Analisis utilizado");
        jLStaticEtiqueta12.setEnabled(false);

        jBBuscarCriterio.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscarCriterio.setText("Buscar un Criterio");
        jBBuscarCriterio.setEnabled(false);
        jBBuscarCriterio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarCriterioActionPerformed(evt);
            }
        });

        jLStaticEtiqueta13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta13.setText("Criterio a utilizar");
        jLStaticEtiqueta13.setEnabled(false);

        jLStaticEtiqueta14.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta14.setText("Etiqueta 6");
        jLStaticEtiqueta14.setEnabled(false);

        jLStaticCampo6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo6.setText("Puntos negros");
        jLStaticCampo6.setEnabled(false);

        jLStaticCampo7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo7.setText("Torrada");
        jLStaticCampo7.setEnabled(false);

        jLStaticCampo8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo8.setText("Color");
        jLStaticCampo8.setEnabled(false);

        jLStaticCampo9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo9.setText("Aroma");
        jLStaticCampo9.setEnabled(false);

        jLStaticCampo10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo10.setText("Tacto");
        jLStaticCampo10.setEnabled(false);

        jCB1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SI", "NO", "ALGUNOS" }));
        jCB1.setEnabled(false);

        jCB2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SI", "NO", "ALGUNOS" }));
        jCB2.setEnabled(false);

        jCB3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "VERDE OSCURO", "VERDE CLARO", "AMARILLENTO" }));
        jCB3.setEnabled(false);

        jCB4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "TIPICO", "OLOR LEVE A HUMO", "OLOR FUERTE A HUMO" }));
        jCB4.setEnabled(false);

        jLStaticCampo11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo11.setText("Degustacion");
        jLStaticCampo11.setEnabled(false);

        jCB5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "CRUJIENTE", "SUAVE", "ESPONJOSO" }));
        jCB5.setEnabled(false);

        jCB6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SI", "NO" }));
        jCB6.setEnabled(false);

        jLStaticCampo12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo12.setText("Comentario (Rellenar si lo hubiere)");
        jLStaticCampo12.setEnabled(false);

        jTADescripcion.setColumns(20);
        jTADescripcion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTADescripcion.setRows(5);
        jTADescripcion.setEnabled(false);
        jScrollPane2.setViewportView(jTADescripcion);

        jLStaticEtiqueta6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta6.setText("un lote");
        jLStaticEtiqueta6.setEnabled(false);

        jBBuscarLote.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscarLote.setText("Buscar un lote");
        jBBuscarLote.setEnabled(false);
        jBBuscarLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarLoteActionPerformed(evt);
            }
        });

        jLStaticEtiqueta4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta4.setText("Lote analizado");
        jLStaticEtiqueta4.setEnabled(false);

        jLStaticEtiqueta5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta5.setText("Lote seleccionado");
        jLStaticEtiqueta5.setEnabled(false);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jRadioButton1.setText("Posee lote asociado");
        jRadioButton1.setEnabled(false);
        jRadioButton1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton1ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jRadioButton2.setText("Posee orden de compra asociada");
        jRadioButton2.setEnabled(false);
        jRadioButton2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButton2ItemStateChanged(evt);
            }
        });

        jLStaticEtiqueta15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta15.setText("Orden de compra seleccionada");
        jLStaticEtiqueta15.setEnabled(false);

        jLStaticEtiqueta16.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta16.setText("una orden");
        jLStaticEtiqueta16.setEnabled(false);

        jBBuscarOrdenDeCompra.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscarOrdenDeCompra.setText("Buscar una orden de compra");
        jBBuscarOrdenDeCompra.setEnabled(false);
        jBBuscarOrdenDeCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarOrdenDeCompraActionPerformed(evt);
            }
        });

        jLStaticEtiqueta17.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta17.setText("Orden de Compra asociada");
        jLStaticEtiqueta17.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLStaticEtiqueta15)
                        .addGap(18, 18, 18)
                        .addComponent(jLStaticEtiqueta16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLStaticEtiqueta17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBuscarOrdenDeCompra))
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLStaticEtiqueta5)
                        .addGap(18, 18, 18)
                        .addComponent(jLStaticEtiqueta6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLStaticEtiqueta4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBBuscarLote)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticEtiqueta4)
                    .addComponent(jBBuscarLote))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticEtiqueta5)
                    .addComponent(jLStaticEtiqueta6))
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticEtiqueta17)
                    .addComponent(jBBuscarOrdenDeCompra))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticEtiqueta15)
                    .addComponent(jLStaticEtiqueta16))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBBuscarLaboratorio)
                                .addGap(18, 18, 18)
                                .addComponent(jLStaticCalendar1)
                                .addGap(24, 24, 24)
                                .addComponent(jC1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLOperacionSeleccionada)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta2)
                                .addGap(18, 18, 18)
                                .addComponent(jLStaticEtiqueta3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLStaticCampo5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTFCampo5))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLStaticCampo3)
                                            .addComponent(jLStaticCampo4)
                                            .addComponent(jLStaticCampo2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTFCampo3, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFCampo2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTFCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLStaticCampo1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTFCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLStaticEtiqueta7)
                                    .addComponent(jLStaticEtiqueta9)
                                    .addComponent(jLStaticEtiqueta8)
                                    .addComponent(jLStaticEtiqueta11)
                                    .addComponent(jLStaticEtiqueta10)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta13)
                                .addGap(18, 18, 18)
                                .addComponent(jLStaticEtiqueta14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBBuscarCriterio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCB6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLStaticCampo8)
                                    .addComponent(jLStaticCampo9)
                                    .addComponent(jLStaticCampo10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLStaticCampo12))
                        .addGap(0, 516, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLOperacionSeleccionada)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLStaticEtiqueta1)
                        .addComponent(jBBuscarLaboratorio))
                    .addComponent(jLStaticCalendar1)
                    .addComponent(jC1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticEtiqueta2)
                    .addComponent(jLStaticEtiqueta3))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticEtiqueta12)
                    .addComponent(jBBuscarCriterio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticEtiqueta13)
                    .addComponent(jLStaticEtiqueta14))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo1)
                    .addComponent(jTFCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo2)
                    .addComponent(jTFCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta9))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo3)
                    .addComponent(jTFCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo4)
                    .addComponent(jTFCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLStaticCampo5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLStaticEtiqueta11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo6)
                    .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo7)
                    .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo8)
                    .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo9)
                    .addComponent(jCB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo10)
                    .addComponent(jCB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo11)
                    .addComponent(jCB6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLStaticCampo12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cabeceraDeVentana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jCBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscar)
                        .addGap(0, 619, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBConcretarAccion)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(cabeceraDeVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBConcretarAccion)
                    .addComponent(jBCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBConcretarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConcretarAccionActionPerformed
       
        try {
            switch ((String)jCBOperacion.getSelectedItem()){
                case "Registrar":
                    if (jRadioButton1.isSelected())
                        unaOrdenDeCompra = null;
                    if (jRadioButton2.isSelected())
                        unLote = null;
                    this.organizacion.registrarAnalisisDeLaboratorio((String) jCB1.getSelectedItem(), (String) jCB2.getSelectedItem(), (String) jCB3.getSelectedItem(), (String) jCB4.getSelectedItem(), (String) jCB5.getSelectedItem(), (String) jCB6.getSelectedItem(), jC1.getCalendar(), unLote, this.unEquipamiento, jTFCampo2.getText(), jTFCampo1.getText(), jTFCampo3.getText(), jTFCampo5.getText(), jTFCampo4.getText(), this.unCriterioSeleccionado, jTADescripcion.getText(), unaOrdenDeCompra);
                    break;
                case "Modificar":
                    if (jRadioButton1.isSelected())
                        unaOrdenDeCompra = null;
                    if (jRadioButton2.isSelected())
                        unLote = null;
                    this.organizacion.modificarAnalisisLaboratorio(unObjetoSeleccionado, unLote, unaOrdenDeCompra);
                    break;
                case "Anular":
                    this.organizacion.anularAnalisisDeLaboratorio(unObjetoSeleccionado);
                    break;
            }
            JOptionPane.showMessageDialog(null, "Operación realizada con exito.");
            deshabilitarTodo();
            limpiarCampos();
            habilitarCamposIniciales();
        } catch (ExcepcionCargaParametros ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: "+ex.getMessage());
        } catch (ExcepcionPersistencia ex) {
            JOptionPane.showMessageDialog(null, "Error en la persistencia: "+ex.getMessage());
        }
        
    }//GEN-LAST:event_jBConcretarAccionActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.deshabilitarTodo();
        this.limpiarCampos();
        this.habilitarCamposIniciales();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCBOperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBOperacionItemStateChanged
        if (!jCBOperacion.getSelectedItem().equals("Seleccionar")){
            this.organizarElementos();
            
        }
        
    }//GEN-LAST:event_jCBOperacionItemStateChanged

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        BuscarAnalisisLaboratorio unaVentana = new BuscarAnalisisLaboratorio(this.organizacion, this, this.trayectoriaActual);
        this.dispose();
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBBuscarLaboratorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarLaboratorioActionPerformed
        BuscarEquipamiento unaVentana = new BuscarEquipamiento(this.organizacion, this, this.trayectoriaActual);
        this.dispose();
    }//GEN-LAST:event_jBBuscarLaboratorioActionPerformed

    private void jBBuscarLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarLoteActionPerformed
        BuscarLote unaVentana = new BuscarLote(this.organizacion, this, this.trayectoriaActual, null);
        this.dispose();
    }//GEN-LAST:event_jBBuscarLoteActionPerformed

    private void jBBuscarCriterioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarCriterioActionPerformed
        BuscarCriterioAnalisisLaboratorio unaVentana = new BuscarCriterioAnalisisLaboratorio(this.organizacion, this, this.trayectoriaActual);
        this.dispose();
    }//GEN-LAST:event_jBBuscarCriterioActionPerformed

    private void jBBuscarOrdenDeCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarOrdenDeCompraActionPerformed
        BuscarOrdenCompra unaVentana = new BuscarOrdenCompra(this.organizacion, this, this.trayectoriaActual);
        this.dispose();
    }//GEN-LAST:event_jBBuscarOrdenDeCompraActionPerformed

    private void jRadioButton1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton1ItemStateChanged
        jLStaticEtiqueta4.setEnabled(jRadioButton1.isSelected());
        jBBuscarLote.setEnabled(jRadioButton1.isSelected());
        jLStaticEtiqueta5.setEnabled(jRadioButton1.isSelected());
        jLStaticEtiqueta6.setEnabled(jRadioButton1.isSelected());
    }//GEN-LAST:event_jRadioButton1ItemStateChanged

    private void jRadioButton2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButton2ItemStateChanged
        jLStaticEtiqueta17.setEnabled(jRadioButton2.isSelected());
        jBBuscarOrdenDeCompra.setEnabled(jRadioButton2.isSelected());
        jLStaticEtiqueta15.setEnabled(jRadioButton2.isSelected());
        jLStaticEtiqueta16.setEnabled(jRadioButton2.isSelected());
    }//GEN-LAST:event_jRadioButton2ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAnalisisLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAnalisisLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAnalisisLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAnalisisLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAnalisisLaboratorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private InterfazGrafica.CabeceraDeVentana cabeceraDeVentana;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBBuscarCriterio;
    private javax.swing.JButton jBBuscarLaboratorio;
    private javax.swing.JButton jBBuscarLote;
    private javax.swing.JButton jBBuscarOrdenDeCompra;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConcretarAccion;
    private com.toedter.calendar.JDateChooser jC1;
    private javax.swing.JComboBox<String> jCB1;
    private javax.swing.JComboBox<String> jCB2;
    private javax.swing.JComboBox<String> jCB3;
    private javax.swing.JComboBox<String> jCB4;
    private javax.swing.JComboBox<String> jCB5;
    private javax.swing.JComboBox<String> jCB6;
    private javax.swing.JComboBox<String> jCBOperacion;
    private javax.swing.JLabel jLOperacionSeleccionada;
    private javax.swing.JLabel jLStaticCalendar1;
    private javax.swing.JLabel jLStaticCampo1;
    private javax.swing.JLabel jLStaticCampo10;
    private javax.swing.JLabel jLStaticCampo11;
    private javax.swing.JLabel jLStaticCampo12;
    private javax.swing.JLabel jLStaticCampo2;
    private javax.swing.JLabel jLStaticCampo3;
    private javax.swing.JLabel jLStaticCampo4;
    private javax.swing.JLabel jLStaticCampo5;
    private javax.swing.JLabel jLStaticCampo6;
    private javax.swing.JLabel jLStaticCampo7;
    private javax.swing.JLabel jLStaticCampo8;
    private javax.swing.JLabel jLStaticCampo9;
    private javax.swing.JLabel jLStaticEtiqueta1;
    private javax.swing.JLabel jLStaticEtiqueta10;
    private javax.swing.JLabel jLStaticEtiqueta11;
    private javax.swing.JLabel jLStaticEtiqueta12;
    private javax.swing.JLabel jLStaticEtiqueta13;
    private javax.swing.JLabel jLStaticEtiqueta14;
    private javax.swing.JLabel jLStaticEtiqueta15;
    private javax.swing.JLabel jLStaticEtiqueta16;
    private javax.swing.JLabel jLStaticEtiqueta17;
    private javax.swing.JLabel jLStaticEtiqueta2;
    private javax.swing.JLabel jLStaticEtiqueta3;
    private javax.swing.JLabel jLStaticEtiqueta4;
    private javax.swing.JLabel jLStaticEtiqueta5;
    private javax.swing.JLabel jLStaticEtiqueta6;
    private javax.swing.JLabel jLStaticEtiqueta7;
    private javax.swing.JLabel jLStaticEtiqueta8;
    private javax.swing.JLabel jLStaticEtiqueta9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JFormattedTextField jTFCampo1;
    private javax.swing.JFormattedTextField jTFCampo2;
    private javax.swing.JFormattedTextField jTFCampo3;
    private javax.swing.JFormattedTextField jTFCampo4;
    private javax.swing.JFormattedTextField jTFCampo5;
    // End of variables declaration//GEN-END:variables

    private void deshabilitarTodo(){
        //TAMBIEN SE HACEN INVISIBLE LOS ELEMENTOS QUE SEAN NECESARIOS
        jBBuscar.setVisible(false);
        UtilidadesInterfazGrafica.deshabilitarCamposEditablesContenedor(new Component[]{jPanel1});
        UtilidadesInterfazGrafica.deshabilitarEtiquetasContenedor(new Component[]{jPanel1});
        deseleccionarBotones();
        
        
        /*
        jLOperacionSeleccionada.setEnabled(false);
        
        jLStaticCampo1.setEnabled(false);
        jLStaticCampo2.setEnabled(false);
        jLStaticCampo3.setEnabled(false);
        jLStaticCampo4.setEnabled(false);
        jLStaticCampo5.setEnabled(false);
        jLStaticCampo6.setEnabled(false);
        jLStaticCampo7.setEnabled(false);
        jLStaticCampo8.setEnabled(false);
        jLStaticCampo9.setEnabled(false);
        jLStaticCampo10.setEnabled(false);
        jLStaticCampo11.setEnabled(false);
        
        jCB1.setEnabled(false);
        jCB2.setEnabled(false);
        jCB3.setEnabled(false);
        jCB4.setEnabled(false);
        jCB5.setEnabled(false);
        jCB6.setEnabled(false);        
        
        jTFCampo1.setEnabled(false);
        jTFCampo2.setEnabled(false);
        jTFCampo3.setEnabled(false);
        jTFCampo4.setEnabled(false);
        jTFCampo5.setEnabled(false);
        
        jLStaticEtiqueta1.setEnabled(false);
        jLStaticEtiqueta2.setEnabled(false);
        jLStaticEtiqueta3.setEnabled(false);
        jLStaticEtiqueta4.setEnabled(false);
        jLStaticEtiqueta5.setEnabled(false);
        jLStaticEtiqueta6.setEnabled(false);
        jLStaticEtiqueta7.setEnabled(false);
        jLStaticEtiqueta8.setEnabled(false);
        jLStaticEtiqueta9.setEnabled(false);
        jLStaticEtiqueta10.setEnabled(true);
        jLStaticEtiqueta11.setEnabled(true);
        jLStaticEtiqueta12.setEnabled(true);
        jLStaticEtiqueta13.setEnabled(true);
        jLStaticEtiqueta14.setEnabled(true);
        
        
        
        jLStaticCalendar1.setEnabled(false);
        
        jC1.setEnabled(false);
        
        jCBOperacion.setEnabled(false);
*/
        jBBuscar.setEnabled(false);
        jBBuscarLote.setEnabled(false);
        jBBuscarCriterio.setEnabled(false);
        jBBuscarLaboratorio.setEnabled(false);
        jBConcretarAccion.setEnabled(false);
        jBCancelar.setEnabled(false);
        
    }
    
    private void limpiarCampos() {
        this.operacionActual = "";
        jTFCampo1.setText("");
        jTFCampo2.setText("");
        jTFCampo3.setText("");
        jTFCampo4.setText("");
        jTFCampo5.setText("");
        
        jC1.setCalendar(null);
        jLStaticEtiqueta3.setText("");
        jLStaticEtiqueta6.setText("");
        jLStaticEtiqueta14.setText("");
        this.unCriterioSeleccionado = null;
        this.unLote = null;
        this.unEquipamiento = null;
        this.unObjetoSeleccionado = null;
    }

    @Override
    public void actualizarUnObjeto(Object unObjeto) {
        
        if (unObjeto instanceof OrdenDeCompra){
            this.unaOrdenDeCompra = (OrdenDeCompra) unObjeto;
            exhibirOrdenDeCompra();
            if (jCBOperacion.getSelectedItem().equals("Registrar"))
                habilitarSeleccionCriterio();
        }
        if (unObjeto instanceof Equipamiento){
            this.unEquipamiento = (Equipamiento) unObjeto;
            exhibirEquipamiento();
        }
        if (unObjeto instanceof Lote){
            this.unLote = (Lote) unObjeto;
            exhibirLote();
            if (jCBOperacion.getSelectedItem().equals("Registrar"))
                habilitarSeleccionCriterio();
        }
        if (unObjeto instanceof AnalisisLaboratorio){
            this.unObjetoSeleccionado = (AnalisisLaboratorio) unObjeto;
            exhibirAnalisis();
            if (!(jCBOperacion.getSelectedItem().equals("Anular"))){
                habilitarRadioButtons();
            }
            habilitarConcresion();
            
        }
        if (unObjeto instanceof CriterioAnalisisLaboratorio){
            this.unCriterioSeleccionado = (CriterioAnalisisLaboratorio) unObjeto;
            exhibirCriterio();
            habilitarConcresion();
        }
    }

    private void prepararAlta() {
        this.operacionActual = "Alta";
        jBConcretarAccion.setText("Registrar un análisis");
        jLOperacionSeleccionada.setText(this.textoAlta);
        jBCancelar.setEnabled(true);
        jLOperacionSeleccionada.setEnabled(true);
        
        jBBuscarLaboratorio.setEnabled(true);
        
        UtilidadesInterfazGrafica.habilitarCamposEditablesContenedor(new Component[]{jPanel1});
        UtilidadesInterfazGrafica.habilitarEtiquetasContenedor(new Component[]{jPanel1});
        UtilidadesInterfazGrafica.deshabilitarEtiquetasContenedor(new Component[]{jPanel2});
        
        /*
        jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        jLStaticCampo8.setEnabled(true);
        jLStaticCampo9.setEnabled(true);
        jLStaticCampo10.setEnabled(true);
        jLStaticCampo11.setEnabled(true);
        
        
        jTFCampo1.setEnabled(true);
        jTFCampo2.setEnabled(true);
        jTFCampo3.setEnabled(true);
        jTFCampo4.setEnabled(true);
        jTFCampo5.setEnabled(true);
        
        jCB1.setEnabled(true);
        jCB2.setEnabled(true);
        jCB3.setEnabled(true);
        jCB4.setEnabled(true);
        jCB5.setEnabled(true);
        jCB6.setEnabled(true);
        
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        jLStaticEtiqueta11.setEnabled(true);
        jLStaticEtiqueta12.setEnabled(true);
        jLStaticEtiqueta13.setEnabled(true);
        jLStaticEtiqueta14.setEnabled(true);
        
        
        jLStaticCalendar1.setEnabled(true);*/
        jC1.setEnabled(false);
        jC1.setCalendar(Calendar.getInstance());
        //jC1.setEnabled(true);
        if (this.unEquipamiento == null)
            return;
        habilitarRadioButtons();

        jBBuscarCriterio.setEnabled(true);
        jBConcretarAccion.setEnabled(true);
        
    }
    
    private void prepararBaja() {
        this.operacionActual = "Anular";
        
        jBBuscar.setEnabled(true);
        jBBuscar.setVisible(true);
        
        jLOperacionSeleccionada.setText(textoBaja);
        jLOperacionSeleccionada.setEnabled(true);
        
        UtilidadesInterfazGrafica.habilitarEtiquetasContenedor(new Component[]{jPanel1});
        /*jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        jLStaticCampo8.setEnabled(true);
        jLStaticCampo9.setEnabled(true);
        jLStaticCampo10.setEnabled(true);
        jLStaticCampo11.setEnabled(true);
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        jLStaticEtiqueta11.setEnabled(true);
        jLStaticEtiqueta12.setEnabled(true);
        jLStaticEtiqueta13.setEnabled(true);
        jLStaticEtiqueta14.setEnabled(true);
        
        jLStaticCalendar1.setEnabled(true);*/
        
        jBCancelar.setEnabled(true);
        
        if (this.unObjetoSeleccionado == null)
            return;
        jBConcretarAccion.setEnabled(true);
        jBConcretarAccion.setText("Anular un análisis de laboratorio");
        
    }

    private void prepararModificacion() {
        this.operacionActual = "Modificacion";
        jLOperacionSeleccionada.setText(this.textoModificacion);
        jLOperacionSeleccionada.setEnabled(true);

        jBBuscar.setVisible(true);
        jBBuscar.setEnabled(true);
        jBCancelar.setEnabled(true);
        
        
        if (unObjetoSeleccionado == null)
            return;
        
        
        UtilidadesInterfazGrafica.habilitarCamposEditablesContenedor(new Component[]{jPanel1});
        habilitarRadioButtons();
        jBConcretarAccion.setEnabled(true);
        jBConcretarAccion.setText("Guardar cambios");

    }

    public String getOperacionActual() {
        return operacionActual;
    }

    private void habilitarCamposIniciales() {
        jLabel12.setEnabled(true);
        jCBOperacion.setEnabled(true);
        this.jCBOperacion.setSelectedItem("Seleccionar");
    }

    private void exhibirEquipamiento() {
        if (unEquipamiento == null)
            return;
        jLStaticEtiqueta3.setText(this.unEquipamiento.getNombre());
    }

    private void exhibirLote() {
        if (unLote==null)
            return;
        jLStaticEtiqueta6.setText(unLote.getEtiqueta());
    }

    private void exhibirAnalisis() {
        if (this.unObjetoSeleccionado == null)
            return;
        jC1.setCalendar(unObjetoSeleccionado.getFechaOrigenC());
        jLStaticEtiqueta3.setText(unObjetoSeleccionado.getLaboratorioAsociado().getNombre());
        if (this.unObjetoSeleccionado.getLoteImplicado() != null)
            jLStaticEtiqueta6.setText(unObjetoSeleccionado.getLoteImplicado().getEtiqueta());
        if (this.unObjetoSeleccionado.getOrdenDeCompraImplicada() != null)
            jLStaticEtiqueta16.setText(""+unObjetoSeleccionado.getOrdenDeCompraImplicada().getId());
        jTFCampo1.setText(""+unObjetoSeleccionado.getPorcentajeSemilla());
        jTFCampo2.setText(""+unObjetoSeleccionado.getPorcentajePalo());
        jTFCampo3.setText(""+unObjetoSeleccionado.getPorcentajePolvo());
        jTFCampo4.setText(""+unObjetoSeleccionado.getPorcentajeHoja());
        jTFCampo5.setText(""+unObjetoSeleccionado.getPorcentajeHumedad());
        
        
    }

    private void habilitarSeleccionCriterio() {
        jLStaticEtiqueta12.setEnabled(true);
        jBBuscarCriterio.setEnabled(true);
    }

    private void exhibirCriterio() {
        if (this.unCriterioSeleccionado == null)
            return;
        jLStaticEtiqueta14.setText(this.unCriterioSeleccionado.getNombre());
        jLStaticEtiqueta13.setEnabled(true);
        jLStaticEtiqueta14.setEnabled(true);
    }

    private void deseleccionarBotones() {
        buttonGroup1.clearSelection();
        jBBuscarOrdenDeCompra.setEnabled(false);
    }

    private void habilitarRadioButtons() {
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
    }

    private void habilitarConcresion() {
        jBConcretarAccion.setEnabled(true);
    }

    private void exhibirOrdenDeCompra() {
        if (unaOrdenDeCompra != null)
            jLStaticEtiqueta16.setText(""+unaOrdenDeCompra.getId());
    }
    

}

