/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import InterfazGrafica.Busqueda.BuscarCriterioAnalisisLaboratorio;
import InterfazGrafica.Busqueda.BuscarGenerico;
import LogicaDeNegocio.CriterioAnalisisLaboratorio;
import LogicaDeNegocio.ExcepcionCargaParametros;
import LogicaDeNegocio.Organizacion;
import LogicaDeNegocio.Proveedor;
import Persistencia.ExcepcionPersistencia;
import java.awt.Component;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class ABMCriteriosAnalisisLaboratorio extends javax.swing.JFrame implements TransferenciaInstancias {
    
    /**
     * Creates new form ABMProveedor
     */
    private Organizacion organizacion;
    private JFrame ventanaAnterior;
    private CriterioAnalisisLaboratorio unObjetoSeleccionado;
    private String trayectoriaActual;
    private String operacionActual;
    
    private final String textoAlta = "Dar de alta un criterio de análisis de laboratorio.";
    private final String textoBaja = "Dar de baja un criterio de análisis de laboratorio.";
    private final String textoModificacion = "Modificar un criterio de análisis de laboratorio.";
    
    public void setUnObjetoSeleccionado(CriterioAnalisisLaboratorio unObjetoSeleccionado) {
        this.unObjetoSeleccionado = unObjetoSeleccionado;
    }
    public ABMCriteriosAnalisisLaboratorio() {
        initComponents();
    }



    public ABMCriteriosAnalisisLaboratorio(Organizacion organizacion, JFrame ventanaAnterior, String trayectoriaAnterior) {
        this.setUndecorated(true);
        initComponents();
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.organizacion = organizacion;
        this.getContentPane().setBackground(ParametrosDeInterfaz.colorFondo);
        setIconImage(new ImageIcon(getClass().getResource(ParametrosDeInterfaz.rutaIcono)).getImage());
        
        trayectoriaActual = trayectoriaAnterior+" - Gestión de criterios de análisis de laboratorio";
        cabeceraDeVentana.configurarCabecera(ventanaAnterior, this, "Gestión de criterios de análisis de laboratorio", this.trayectoriaActual, organizacion.getUsuarioActivo().getApellido()+", "+organizacion.getUsuarioActivo().getNombre());
        
        this.setVisible(true); 
        jBBuscar.setVisible(false);
        
        this.ventanaAnterior = ventanaAnterior;
        habilitarCamposIniciales();
        ParametrosDeInterfaz.configurarVentana(this);
    }
    private void organizarElementos(){
        this.deshabilitarTodo();
        switch((String)jCBOperacion.getSelectedItem()){
            case "Alta":
                prepararAlta();
                break;
            case "Baja":
                prepararBaja();
                break;
            case "Modificacion":
                prepararModificacion();
                break;
            default:
                limpiarCampos();
                break;
                
        }
        //this.pack();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBConcretarAccion = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jCBOperacion = new javax.swing.JComboBox<>();
        jBBuscar = new javax.swing.JButton();
        cabeceraDeVentana = new InterfazGrafica.CabeceraDeVentana();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLEstado = new javax.swing.JLabel();
        jCBEstado = new javax.swing.JComboBox<>();
        jLStaticCalendar1 = new javax.swing.JLabel();
        jC1 = new com.toedter.calendar.JDateChooser();
        jLOperacionSeleccionada = new javax.swing.JLabel();
        jLStaticCampo1 = new javax.swing.JLabel();
        jTFCampo1 = new javax.swing.JTextField();
        jLStaticEtiqueta10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLStaticEtiqueta3 = new javax.swing.JLabel();
        jLStaticEtiqueta8 = new javax.swing.JLabel();
        jLStaticEtiqueta9 = new javax.swing.JLabel();
        jLStaticEtiqueta5 = new javax.swing.JLabel();
        jLStaticEtiqueta7 = new javax.swing.JLabel();
        jLStaticCampo2 = new javax.swing.JLabel();
        jLStaticCampo8 = new javax.swing.JLabel();
        jLStaticCampo3 = new javax.swing.JLabel();
        jLStaticCampo4 = new javax.swing.JLabel();
        jLStaticCampo9 = new javax.swing.JLabel();
        jLStaticCampo10 = new javax.swing.JLabel();
        jLStaticCampo11 = new javax.swing.JLabel();
        NumberFormat formateadorCampoFloat = NumberFormat.getInstance();
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo2 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo3 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo4 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo5 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo6 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        jLStaticCampo7 = new javax.swing.JLabel();
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo7 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo8 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        jLStaticEtiqueta11 = new javax.swing.JLabel();
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo9 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo10 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        formateadorCampoFloat.setGroupingUsed(true);
        formateadorCampoFloat.setMinimumFractionDigits(3);
        formateadorCampoFloat.setParseIntegerOnly(false);
        jTFCampo11 = new javax.swing.JFormattedTextField(formateadorCampoFloat);
        jLStaticCampo6 = new javax.swing.JLabel();
        jLStaticCampo5 = new javax.swing.JLabel();
        jLStaticEtiqueta2 = new javax.swing.JLabel();
        jLStaticEtiqueta6 = new javax.swing.JLabel();
        jLStaticEtiqueta1 = new javax.swing.JLabel();
        jLStaticEtiqueta4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCB1 = new javax.swing.JComboBox<>();
        jLStaticCB1 = new javax.swing.JLabel();
        jCB2 = new javax.swing.JComboBox<>();
        jLStaticCB2 = new javax.swing.JLabel();
        jCB5 = new javax.swing.JComboBox<>();
        jLStaticCB5 = new javax.swing.JLabel();
        jLStaticCB3 = new javax.swing.JLabel();
        jCB3 = new javax.swing.JComboBox<>();
        jCB6 = new javax.swing.JComboBox<>();
        jLStaticCB6 = new javax.swing.JLabel();
        jCB4 = new javax.swing.JComboBox<>();
        jLStaticCB4 = new javax.swing.JLabel();
        jCB7 = new javax.swing.JComboBox<>();
        jLStaticCB7 = new javax.swing.JLabel();
        jLStaticCampo12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jBConcretarAccion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBConcretarAccion.setText("Aceptar");
        jBConcretarAccion.setEnabled(false);
        jBConcretarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConcretarAccionActionPerformed(evt);
            }
        });

        jBCancelar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setText("Seleccione una operacion");

        jCBOperacion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Alta", "Baja", "Modificacion" }));
        jCBOperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBOperacionItemStateChanged(evt);
            }
        });

        jBBuscar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscar.setText("Buscar un criterio de Analisis de Laboratorio");
        jBBuscar.setEnabled(false);
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLEstado.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstado.setText("Estado");
        jLEstado.setEnabled(false);

        jCBEstado.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Activo", "Baja" }));
        jCBEstado.setEnabled(false);

        jLStaticCalendar1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCalendar1.setText("Fecha de origen");
        jLStaticCalendar1.setEnabled(false);

        jC1.setEnabled(false);
        jC1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLOperacionSeleccionada.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLOperacionSeleccionada.setText("Operación sobre un Concepto");
        jLOperacionSeleccionada.setEnabled(false);

        jLStaticCampo1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo1.setText("Nombre");
        jLStaticCampo1.setEnabled(false);

        jTFCampo1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo1.setEnabled(false);

        jLStaticEtiqueta10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta10.setText("Ingrese los intervalos de valores que deben verificar los analisis de laboratorio que verifiquen este criterio");
        jLStaticEtiqueta10.setEnabled(false);

        jLStaticEtiqueta3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta3.setText("%");
        jLStaticEtiqueta3.setEnabled(false);

        jLStaticEtiqueta8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta8.setText("%");
        jLStaticEtiqueta8.setEnabled(false);

        jLStaticEtiqueta9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta9.setText("%");
        jLStaticEtiqueta9.setEnabled(false);

        jLStaticEtiqueta5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta5.setText("%");
        jLStaticEtiqueta5.setEnabled(false);

        jLStaticEtiqueta7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta7.setText("%");
        jLStaticEtiqueta7.setEnabled(false);

        jLStaticCampo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo2.setText("Porcentaje inferior admitido de semilla");
        jLStaticCampo2.setEnabled(false);

        jLStaticCampo8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo8.setText("Porcentaje inferior admitido de hoja");
        jLStaticCampo8.setEnabled(false);

        jLStaticCampo3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo3.setText("Porcentaje superior admitido de semilla");
        jLStaticCampo3.setEnabled(false);

        jLStaticCampo4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo4.setText("Porcentaje inferior admitido de palo");
        jLStaticCampo4.setEnabled(false);

        jLStaticCampo9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo9.setText("Porcentaje superior admitido de hoja");
        jLStaticCampo9.setEnabled(false);

        jLStaticCampo10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo10.setText("Porcentaje superior admitido de humedad");
        jLStaticCampo10.setEnabled(false);

        jLStaticCampo11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo11.setText("Porcentaje inferior admitido de humedad");
        jLStaticCampo11.setEnabled(false);

        jTFCampo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCampo7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo7.setText("Porcentaje superior admitido de polvo");
        jLStaticCampo7.setEnabled(false);

        jTFCampo7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta11.setText("%");
        jLStaticEtiqueta11.setEnabled(false);

        jTFCampo9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCampo6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo6.setText("Porcentaje inferior admitido de polvo");
        jLStaticCampo6.setEnabled(false);

        jLStaticCampo5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo5.setText("Porcentaje superior admitido de palo");
        jLStaticCampo5.setEnabled(false);

        jLStaticEtiqueta2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta2.setText("%");
        jLStaticEtiqueta2.setEnabled(false);

        jLStaticEtiqueta6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta6.setText("%");
        jLStaticEtiqueta6.setEnabled(false);

        jLStaticEtiqueta1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta1.setText("%");
        jLStaticEtiqueta1.setEnabled(false);

        jLStaticEtiqueta4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta4.setText("%");
        jLStaticEtiqueta4.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLStaticCampo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLStaticEtiqueta1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCampo5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCampo4))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStaticEtiqueta2)
                            .addComponent(jLStaticEtiqueta3)
                            .addComponent(jLStaticEtiqueta4)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCampo7))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStaticEtiqueta5)
                            .addComponent(jLStaticEtiqueta6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCampo11))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCampo10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStaticEtiqueta8)
                            .addComponent(jLStaticEtiqueta9)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCampo9))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCampo8, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStaticEtiqueta11)
                            .addComponent(jLStaticEtiqueta7))))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo2)
                    .addComponent(jTFCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta1))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo3)
                    .addComponent(jLStaticEtiqueta2)
                    .addComponent(jTFCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo4)
                    .addComponent(jTFCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta3))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo5)
                    .addComponent(jTFCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta4))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo6)
                    .addComponent(jTFCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta5))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo7)
                    .addComponent(jTFCampo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta6))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo8)
                    .addComponent(jTFCampo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta11))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo9)
                    .addComponent(jTFCampo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta7))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo11)
                    .addComponent(jTFCampo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta8))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo10)
                    .addComponent(jTFCampo11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticEtiqueta9))
                .addGap(20, 20, 20))
        );

        jCB1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SI", "NO", "ALGUNOS" }));
        jCB1.setEnabled(false);

        jLStaticCB1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB1.setText("Puntos negros");
        jLStaticCB1.setEnabled(false);

        jCB2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SI", "NO", "ALGUNOS" }));
        jCB2.setEnabled(false);

        jLStaticCB2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB2.setText("Torrada");
        jLStaticCB2.setEnabled(false);

        jCB5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "CRUJIENTE", "SUAVE", "ESPONJOSO" }));
        jCB5.setEnabled(false);

        jLStaticCB5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB5.setText("Tacto");
        jLStaticCB5.setEnabled(false);

        jLStaticCB3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB3.setText("Color");
        jLStaticCB3.setEnabled(false);

        jCB3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "VERDE OSCURO", "VERDE CLARO", "AMARILLENTO" }));
        jCB3.setEnabled(false);

        jCB6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SI", "NO" }));
        jCB6.setEnabled(false);

        jLStaticCB6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB6.setText("Degustacion");
        jLStaticCB6.setEnabled(false);

        jCB4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "TIPICO", "OLOR LEVE A HUMO", "OLOR FUERTE A HUMO" }));
        jCB4.setEnabled(false);

        jLStaticCB4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB4.setText("Aroma");
        jLStaticCB4.setEnabled(false);

        jCB7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "YCV", "YCE", "YM" }));
        jCB7.setEnabled(false);

        jLStaticCB7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB7.setText("Tipo de Lote");
        jLStaticCB7.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLStaticCB7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLStaticCB1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLStaticCB2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLStaticCB3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLStaticCB4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLStaticCB5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLStaticCB6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCB7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCB6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCB7)
                    .addComponent(jCB7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCB1)
                    .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCB2)
                    .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCB3)
                    .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCB4)
                    .addComponent(jCB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCB5)
                    .addComponent(jCB5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCB6)
                    .addComponent(jCB6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jLStaticCampo12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo12.setText("Descripción");
        jLStaticCampo12.setEnabled(false);

        jTADescripcion.setColumns(20);
        jTADescripcion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTADescripcion.setRows(5);
        jTADescripcion.setEnabled(false);
        jScrollPane2.setViewportView(jTADescripcion);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLOperacionSeleccionada)
                    .addComponent(jLStaticEtiqueta10)
                    .addComponent(jLStaticCampo12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo1)
                                .addGap(12, 12, 12)
                                .addComponent(jTFCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLStaticCalendar1))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jC1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1428, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLOperacionSeleccionada)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEstado)
                    .addComponent(jC1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticCalendar1)
                    .addComponent(jTFCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticCampo1))
                .addGap(20, 20, 20)
                .addComponent(jLStaticCampo12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLStaticEtiqueta10)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jCBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(cabeceraDeVentana, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1521, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBConcretarAccion)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(cabeceraDeVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 793, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBConcretarAccion)
                    .addComponent(jBCancelar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBConcretarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConcretarAccionActionPerformed
       
        try {
            switch ((String)jCBOperacion.getSelectedItem()){
                case "Alta":
                    this.organizacion.registrarCriterioDeAnalisisDeLaboratorio(jTFCampo1.getText(), jTADescripcion.getText(), jC1.getCalendar(),
                            (String) jCB7.getSelectedItem(), (String) jCB1.getSelectedItem(), (String) jCB2.getSelectedItem(), (String) jCB3.getSelectedItem(), (String) jCB4.getSelectedItem(), (String) jCB5.getSelectedItem(), (String) jCB6.getSelectedItem(), jTFCampo2.getText(), jTFCampo3.getText(), jTFCampo4.getText(), jTFCampo5.getText(), jTFCampo6.getText(), jTFCampo7.getText(), jTFCampo10.getText(), jTFCampo11.getText(), jTFCampo8.getText(), jTFCampo9.getText());
                    break;
                case "Baja":
                    this.organizacion.darDeBajaUnCriterio(this.unObjetoSeleccionado);
                    break;
                case "Modificacion":
                    this.organizacion.modificarCriterioDeAnalisis(this.unObjetoSeleccionado, (String) jCBEstado.getSelectedItem());
                    break;
            }
            JOptionPane.showMessageDialog(null, "Operación realizada con exito.");
            deshabilitarTodo();
            limpiarCampos();
            habilitarCamposIniciales();
        } catch (ExcepcionCargaParametros ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: "+ex.getMessage());
        } catch (ExcepcionPersistencia ex) {
            JOptionPane.showMessageDialog(null, "Error en la persistencia: "+ex.getMessage());
        }
        
    }//GEN-LAST:event_jBConcretarAccionActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.deshabilitarTodo();
        this.limpiarCampos();
        this.habilitarCamposIniciales();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCBOperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBOperacionItemStateChanged
        if (!jCBOperacion.getSelectedItem().equals("Seleccionar")){
            this.organizarElementos();
            
        }
        
    }//GEN-LAST:event_jCBOperacionItemStateChanged

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        BuscarCriterioAnalisisLaboratorio unaVentana = new BuscarCriterioAnalisisLaboratorio(this.organizacion, this, this.trayectoriaActual);
        this.dispose();
    }//GEN-LAST:event_jBBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMCriteriosAnalisisLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMCriteriosAnalisisLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMCriteriosAnalisisLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMCriteriosAnalisisLaboratorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMCriteriosAnalisisLaboratorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private InterfazGrafica.CabeceraDeVentana cabeceraDeVentana;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConcretarAccion;
    private com.toedter.calendar.JDateChooser jC1;
    private javax.swing.JComboBox<String> jCB1;
    private javax.swing.JComboBox<String> jCB2;
    private javax.swing.JComboBox<String> jCB3;
    private javax.swing.JComboBox<String> jCB4;
    private javax.swing.JComboBox<String> jCB5;
    private javax.swing.JComboBox<String> jCB6;
    private javax.swing.JComboBox<String> jCB7;
    private javax.swing.JComboBox<String> jCBEstado;
    private javax.swing.JComboBox<String> jCBOperacion;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLOperacionSeleccionada;
    private javax.swing.JLabel jLStaticCB1;
    private javax.swing.JLabel jLStaticCB2;
    private javax.swing.JLabel jLStaticCB3;
    private javax.swing.JLabel jLStaticCB4;
    private javax.swing.JLabel jLStaticCB5;
    private javax.swing.JLabel jLStaticCB6;
    private javax.swing.JLabel jLStaticCB7;
    private javax.swing.JLabel jLStaticCalendar1;
    private javax.swing.JLabel jLStaticCampo1;
    private javax.swing.JLabel jLStaticCampo10;
    private javax.swing.JLabel jLStaticCampo11;
    private javax.swing.JLabel jLStaticCampo12;
    private javax.swing.JLabel jLStaticCampo2;
    private javax.swing.JLabel jLStaticCampo3;
    private javax.swing.JLabel jLStaticCampo4;
    private javax.swing.JLabel jLStaticCampo5;
    private javax.swing.JLabel jLStaticCampo6;
    private javax.swing.JLabel jLStaticCampo7;
    private javax.swing.JLabel jLStaticCampo8;
    private javax.swing.JLabel jLStaticCampo9;
    private javax.swing.JLabel jLStaticEtiqueta1;
    private javax.swing.JLabel jLStaticEtiqueta10;
    private javax.swing.JLabel jLStaticEtiqueta11;
    private javax.swing.JLabel jLStaticEtiqueta2;
    private javax.swing.JLabel jLStaticEtiqueta3;
    private javax.swing.JLabel jLStaticEtiqueta4;
    private javax.swing.JLabel jLStaticEtiqueta5;
    private javax.swing.JLabel jLStaticEtiqueta6;
    private javax.swing.JLabel jLStaticEtiqueta7;
    private javax.swing.JLabel jLStaticEtiqueta8;
    private javax.swing.JLabel jLStaticEtiqueta9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JTextField jTFCampo1;
    private javax.swing.JFormattedTextField jTFCampo10;
    private javax.swing.JFormattedTextField jTFCampo11;
    private javax.swing.JFormattedTextField jTFCampo2;
    private javax.swing.JFormattedTextField jTFCampo3;
    private javax.swing.JFormattedTextField jTFCampo4;
    private javax.swing.JFormattedTextField jTFCampo5;
    private javax.swing.JFormattedTextField jTFCampo6;
    private javax.swing.JFormattedTextField jTFCampo7;
    private javax.swing.JFormattedTextField jTFCampo8;
    private javax.swing.JFormattedTextField jTFCampo9;
    // End of variables declaration//GEN-END:variables

    private void deshabilitarTodo(){
        //TAMBIEN SE HACEN INVISIBLE LOS ELEMENTOS QUE SEAN NECESARIOS
        jBBuscar.setVisible(false);
        
        UtilidadesInterfazGrafica.habilitarFocusCamposEditablesContenedor(new Component[]{jPanel1});
        UtilidadesInterfazGrafica.deshabilitarCamposEditablesContenedor(new Component[]{jPanel1});
        UtilidadesInterfazGrafica.deshabilitarEtiquetasContenedor(new Component[]{jPanel1});
        /*
        jLOperacionSeleccionada.setEnabled(false);
        
        jLStaticCampo1.setEnabled(false);
        jLStaticCampo2.setEnabled(false);
        jLStaticCampo3.setEnabled(false);
        jLStaticCampo4.setEnabled(false);
        jLStaticCampo5.setEnabled(false);
        jLStaticCampo6.setEnabled(false);
        jLStaticCampo7.setEnabled(false);
        jLStaticCampo8.setEnabled(false);
        jLStaticCampo9.setEnabled(false);
        jLStaticCampo10.setEnabled(false);
        jLStaticCampo11.setEnabled(false);
        jLStaticCampo12.setEnabled(false);
        
        jTFCampo1.setEnabled(false);
        jTFCampo3.setEnabled(false);
        jTFCampo3.setEnabled(false);
        jTFCampo4.setEnabled(false);
        jTFCampo5.setEnabled(false);
        jTFCampo6.setEnabled(false);
        jTFCampo7.setEnabled(false);
        
        jLEstado.setEnabled(false);
        jLStaticCB1.setEnabled(false);
        jLStaticCB2.setEnabled(false);
        jLStaticCB3.setEnabled(false);
        jLStaticCB4.setEnabled(false);
        jLStaticCB5.setEnabled(false);
        jLStaticCB6.setEnabled(false);
        
        jTADescripcion.setEnabled(false);
        
        jCBEstado.setEnabled(false);
        jCB1.setEnabled(false);
        jCB2.setEnabled(false);
        jCB3.setEnabled(false);
        jCB4.setEnabled(false);
        jCB5.setEnabled(false);
        jCB6.setEnabled(false);
        
        jLStaticEtiqueta1.setEnabled(false);
        jLStaticEtiqueta2.setEnabled(false);
        jLStaticEtiqueta3.setEnabled(false);
        jLStaticEtiqueta4.setEnabled(false);
        jLStaticEtiqueta5.setEnabled(false);
        jLStaticEtiqueta6.setEnabled(false);
        jLStaticEtiqueta7.setEnabled(false);
        jLStaticEtiqueta8.setEnabled(false);
        jLStaticEtiqueta9.setEnabled(false);
        jLStaticEtiqueta10.setEnabled(false);
        jLStaticEtiqueta11.setEnabled(false);
        
        
        jLStaticCalendar1.setEnabled(false);
        
        jC1.setEnabled(false);
*/
        jCBOperacion.setEnabled(false);
        
        jBBuscar.setEnabled(false);
        jBConcretarAccion.setEnabled(false);
        jBCancelar.setEnabled(false);
        
    }
    
    private void limpiarCampos() {
                this.operacionActual = "";
                
                jTFCampo1.setText("");
                jTFCampo3.setText("");
                jTFCampo3.setText("");
                jTFCampo4.setText("");
                jTFCampo5.setText("");
                jTFCampo6.setText("");
                jTFCampo7.setText("");
                jTFCampo8.setText("");
                jTFCampo9.setText("");
                jTFCampo10.setText("");
                jTFCampo11.setText("");
                
                jTADescripcion.setText("");
                
                jC1.setCalendar(null);
                jCBEstado.setSelectedItem("Seleccionar");
                
                jCB1.setSelectedItem("Seleccionar");
                jCB2.setSelectedItem("Seleccionar");
                jCB3.setSelectedItem("Seleccionar");
                jCB4.setSelectedItem("Seleccionar");
                jCB5.setSelectedItem("Seleccionar");
                jCB6.setSelectedItem("Seleccionar");
                jCB7.setSelectedItem("Seleccionar");
                this.unObjetoSeleccionado = null;
    }

    @Override
    public void actualizarUnObjeto(Object unObjeto) {
        CriterioAnalisisLaboratorio unCriterioDeAnalisisDeLaboratorio = (CriterioAnalisisLaboratorio) unObjeto;
        this.unObjetoSeleccionado = unCriterioDeAnalisisDeLaboratorio;
        
        exhibirCriterioDeAnalisisDeLaboratorio();
        
        organizarElementos();
        jBConcretarAccion.setEnabled(true);
        jBCancelar.setEnabled(true);
        //this.pack();
    }

    private void prepararAlta() {
        this.operacionActual = "Alta";
        jBConcretarAccion.setText("Dar de alta");
        jLOperacionSeleccionada.setText(this.textoAlta);
        
        UtilidadesInterfazGrafica.habilitarEtiquetasContenedor(new Component[]{jPanel1});
        UtilidadesInterfazGrafica.habilitarCamposEditablesContenedor(new Component[]{jPanel1});
        
        jC1.setCalendar(Calendar.getInstance());
        jCBEstado.setSelectedItem("Activo");
        jC1.setEnabled(false);
        jCBEstado.setEnabled(false);
        
        /*
        jLOperacionSeleccionada.setEnabled(true);
        jTADescripcion.setEnabled(true);
        jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        jLStaticCampo8.setEnabled(true);
        jLStaticCampo9.setEnabled(true);
        jLStaticCampo10.setEnabled(true);
        jLStaticCampo11.setEnabled(true);
        jLStaticCampo12.setEnabled(true);
        
        jTFCampo1.setEnabled(true);
        jTFCampo3.setEnabled(true);
        jTFCampo3.setEnabled(true);
        jTFCampo4.setEnabled(true);
        jTFCampo5.setEnabled(true);
        jTFCampo6.setEnabled(true);
        jTFCampo7.setEnabled(true);
        jTFCampo8.setEnabled(true);
        jTFCampo9.setEnabled(true);
        jTFCampo10.setEnabled(true);
        jTFCampo11.setEnabled(true);
        
        //jLEstado.setEnabled(true); EL ESTADO NO SE ELIGE CUANDO SE DA DE ALTA.
        jLStaticCB1.setEnabled(true);
        jLStaticCB2.setEnabled(true);
        jLStaticCB3.setEnabled(true);
        jLStaticCB4.setEnabled(true);
        jLStaticCB5.setEnabled(true);
        jLStaticCB6.setEnabled(true);
        
        //jCBEstado.setEnabled(true); EL ESTADO NO SE ELIGE CUANDO SE DA DE ALTA.
        jCB1.setEnabled(true);
        jCB2.setEnabled(true);
        jCB3.setEnabled(true);
        jCB4.setEnabled(true);
        jCB5.setEnabled(true);
        jCB6.setEnabled(true);
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        jLStaticEtiqueta11.setEnabled(true);
        
        jLStaticCalendar1.setEnabled(true);
        
        //jC1.setEnabled(true);
        
        */
        
        jBConcretarAccion.setEnabled(true);
        jBCancelar.setEnabled(true);
    }
    
    private void prepararBaja() {
        this.operacionActual = "Baja";
        
        jBBuscar.setEnabled(true);
        jBBuscar.setVisible(true);
        
        jLOperacionSeleccionada.setText(textoBaja);
        jLOperacionSeleccionada.setEnabled(true);
        
        UtilidadesInterfazGrafica.habilitarEtiquetasContenedor(new Component[]{jPanel1});
        UtilidadesInterfazGrafica.habilitarCamposEditablesContenedor(new Component[]{jPanel1});
        UtilidadesInterfazGrafica.deshabilitarFocusCamposEditablesContenedor(new Component[]{jPanel1});
        
        jBCancelar.setEnabled(true);
        
        if (this.unObjetoSeleccionado == null)
            return;
        jBConcretarAccion.setEnabled(true);
        jBConcretarAccion.setText("Dar de baja");
        
    }

    private void prepararModificacion() {
        this.operacionActual = "Modificacion";
        jLOperacionSeleccionada.setText(this.textoModificacion);
        jLOperacionSeleccionada.setEnabled(true);

        jBBuscar.setVisible(true);
        jBBuscar.setEnabled(true);
        jBCancelar.setEnabled(true);
        
        
        if (unObjetoSeleccionado == null)
            return;
        UtilidadesInterfazGrafica.habilitarEtiquetasContenedor(new Component[]{jPanel1});
        UtilidadesInterfazGrafica.habilitarCamposEditablesContenedor(new Component[]{jPanel1});
        UtilidadesInterfazGrafica.deshabilitarFocusCamposEditablesContenedor(new Component[]{jPanel1});
        habilitarFocusCamposEditables();
        jC1.setEnabled(false);
        jCBEstado.setEnabled(true);
        jTADescripcion.setEnabled(true);
        
        /*
        jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        jLStaticCampo8.setEnabled(true);
        
        jTFCampo1.setEnabled(true); //SI ALGUN CAMPO NO SE PUDIERA MODIFICAR, (POR EJEMPLO, FECHA DE CREACION, CONCEPTO ASOCIADO, ETC. BORRAR ESTAS LINEAS)
        jTFCampo3.setEnabled(true);
        jTFCampo3.setEnabled(true);
        jTFCampo4.setEnabled(true);
        jTFCampo5.setEnabled(true);
        jTFCampo6.setEnabled(true);
        jTFCampo7.setEnabled(true);
        
        jLEstado.setEnabled(true);
        jLStaticCB1.setEnabled(true);
        jLStaticCB2.setEnabled(true);
        jLStaticCB3.setEnabled(true);
        
        jCBEstado.setEnabled(true);
        jCB1.setEnabled(true);
        jCB2.setEnabled(true);
        jCB3.setEnabled(true);
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        
        jLStaticCalendar1.setEnabled(true);
        
        jC1.setEnabled(true);
*/
        
        jBConcretarAccion.setEnabled(true);
        jBConcretarAccion.setText("Guardar cambios");

    }

    public String getOperacionActual() {
        return operacionActual;
    }

    private void habilitarCamposIniciales() {
        jLabel12.setEnabled(true);
        jCBOperacion.setEnabled(true);
        this.jCBOperacion.setSelectedItem("Seleccionar");
    }

    private void exhibirCriterioDeAnalisisDeLaboratorio() {
        if (this.unObjetoSeleccionado == null)
            return;
        jTFCampo1.setText(unObjetoSeleccionado.getNombre());
        jC1.setCalendar(unObjetoSeleccionado.getFechaOrigenC());
        jTADescripcion.setText(unObjetoSeleccionado.getDescripcion());
        jTFCampo2.setText(""+unObjetoSeleccionado.getPorcentajeSemillaLimiteInferior());
        jTFCampo3.setText(""+unObjetoSeleccionado.getPorcentajeSemillaLimiteSuperior());
        jTFCampo4.setText(""+unObjetoSeleccionado.getPorcentajePaloLimiteInferior());
        jTFCampo5.setText(""+unObjetoSeleccionado.getPorcentajePaloLimiteSuperior());
        jTFCampo6.setText(""+unObjetoSeleccionado.getPorcentajePolvoLimiteInferior());
        jTFCampo7.setText(""+unObjetoSeleccionado.getPorcentajePolvoLimiteSuperior());
        jTFCampo8.setText(""+unObjetoSeleccionado.getPorcentajeHojaLimiteInferior());
        jTFCampo9.setText(""+unObjetoSeleccionado.getPorcentajeHojaLimiteSuperior());
        jTFCampo10.setText(""+unObjetoSeleccionado.getPorcentajeHumedadLimiteInferior());
        jTFCampo11.setText(""+unObjetoSeleccionado.getPorcentajeHumedadLimiteSuperior());
        
        jCB1.setSelectedItem(unObjetoSeleccionado.getPuntosNegros());
        jCB2.setSelectedItem(unObjetoSeleccionado.getTorrada());
        jCB3.setSelectedItem(unObjetoSeleccionado.getColor());
        jCB4.setSelectedItem(unObjetoSeleccionado.getAroma());
        jCB5.setSelectedItem(unObjetoSeleccionado.getTacto());
        jCB6.setSelectedItem(unObjetoSeleccionado.getDegustacion());
        jCB6.setSelectedItem(unObjetoSeleccionado.getTipoLote());
    }

    private void habilitarFocusCamposEditables() {
        jTADescripcion.setFocusable(true);
        jCBEstado.setEnabled(true);
    }
    

}

