/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import InterfazGrafica.Busqueda.BuscarGenerico;
import LogicaDeNegocio.Organizacion;
import LogicaDeNegocio.Proveedor;
import java.awt.Component;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author usuario
 */
public class ABMGenerico extends javax.swing.JFrame implements TransferenciaInstancias {
    
    /**
     * Creates new form ABMProveedor
     */
    private Organizacion organizacion;
    private JFrame ventanaAnterior;
    private Proveedor unObjetoSeleccionado;
    private String trayectoriaActual;
    private String operacionActual;
    
    private final String textoAlta = "Dar de alta un CONCEPTO";
    private final String textoBaja = "Dar de baja un CONCEPTO";
    private final String textoModificacion = "Modificar un CONCEPTO";
    
    public void setUnObjetoSeleccionado(Proveedor unObjetoSeleccionado) {
        this.unObjetoSeleccionado = unObjetoSeleccionado;
    }
    public ABMGenerico() {
        initComponents();
    }



    ABMGenerico(Organizacion organizacion, JFrame ventanaAnterior, String trayectoriaAnterior) {
        this.setUndecorated(true);
        initComponents();
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.organizacion = organizacion;
        this.getContentPane().setBackground(ParametrosDeInterfaz.colorFondo);
        setIconImage(new ImageIcon(getClass().getResource(ParametrosDeInterfaz.rutaIcono)).getImage());
        
        trayectoriaActual = trayectoriaAnterior+" - Gestión de ALGUN CONCEPTO";
        cabeceraDeVentana.configurarCabecera(ventanaAnterior, this, "Gestión de ALGUN CONCEPTO", this.trayectoriaActual, organizacion.getUsuarioActivo().getApellido()+", "+organizacion.getUsuarioActivo().getNombre());
        
        

        this.setVisible(true); 
        jBBuscar.setVisible(false);
        
        
        this.ventanaAnterior = ventanaAnterior;
        habilitarCamposIniciales();
        ParametrosDeInterfaz.configurarVentana(this);
    }
    private void organizarElementos(){
        this.deshabilitarTodo();
        switch((String)jCBOperacion.getSelectedItem()){
            case "Alta":
                prepararAlta();
                break;
            case "Baja":
                prepararBaja();
                break;
            case "Modificacion":
                prepararModificacion();
                break;
            default:
                limpiarCampos();
                break;
                
        }
        //this.pack();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBConcretarAccion = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jCBOperacion = new javax.swing.JComboBox<>();
        jBBuscar = new javax.swing.JButton();
        cabeceraDeVentana = new InterfazGrafica.CabeceraDeVentana();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jTFCampo2 = new javax.swing.JTextField();
        jLEstado = new javax.swing.JLabel();
        jCBEstado = new javax.swing.JComboBox<>();
        jLStaticCampo3 = new javax.swing.JLabel();
        jTFCampo3 = new javax.swing.JTextField();
        jCB1 = new javax.swing.JComboBox<>();
        jLStaticCB1 = new javax.swing.JLabel();
        jCB2 = new javax.swing.JComboBox<>();
        jLStaticCB2 = new javax.swing.JLabel();
        jLStaticCampo4 = new javax.swing.JLabel();
        jTFCampo4 = new javax.swing.JTextField();
        jLStaticCB3 = new javax.swing.JLabel();
        jCB3 = new javax.swing.JComboBox<>();
        jLStaticCalendar1 = new javax.swing.JLabel();
        jC1 = new com.toedter.calendar.JDateChooser();
        jLStaticCalendar2 = new javax.swing.JLabel();
        jC2 = new com.toedter.calendar.JDateChooser();
        jLStaticCalendar3 = new javax.swing.JLabel();
        jC3 = new com.toedter.calendar.JDateChooser();
        jC4 = new com.toedter.calendar.JDateChooser();
        jLStaticCalendar4 = new javax.swing.JLabel();
        jLStaticCampo7 = new javax.swing.JLabel();
        jTFCampo7 = new javax.swing.JTextField();
        jTFCampo6 = new javax.swing.JTextField();
        jLStaticCampo6 = new javax.swing.JLabel();
        jLStaticCampo5 = new javax.swing.JLabel();
        jTFCampo5 = new javax.swing.JTextField();
        jLOperacionSeleccionada = new javax.swing.JLabel();
        jLStaticEtiqueta2 = new javax.swing.JLabel();
        jLStaticEtiqueta6 = new javax.swing.JLabel();
        jLStaticEtiqueta1 = new javax.swing.JLabel();
        jLStaticEtiqueta4 = new javax.swing.JLabel();
        jLStaticCampo1 = new javax.swing.JLabel();
        jTFCampo1 = new javax.swing.JTextField();
        jLStaticEtiqueta3 = new javax.swing.JLabel();
        jLStaticEtiqueta8 = new javax.swing.JLabel();
        jLStaticEtiqueta9 = new javax.swing.JLabel();
        jLStaticEtiqueta5 = new javax.swing.JLabel();
        jLStaticEtiqueta7 = new javax.swing.JLabel();
        jLStaticEtiqueta10 = new javax.swing.JLabel();
        jLStaticCampo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jBConcretarAccion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBConcretarAccion.setText("Aceptar");
        jBConcretarAccion.setEnabled(false);
        jBConcretarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConcretarAccionActionPerformed(evt);
            }
        });

        jBCancelar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setText("Seleccione una operacion");

        jCBOperacion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Alta", "Baja", "Modificacion" }));
        jCBOperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBOperacionItemStateChanged(evt);
            }
        });

        jBBuscar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscar.setText("Buscar un Objeto");
        jBBuscar.setEnabled(false);
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTFCampo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo2.setEnabled(false);

        jLEstado.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstado.setText("Estado");
        jLEstado.setEnabled(false);

        jCBEstado.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Baja" }));
        jCBEstado.setEnabled(false);

        jLStaticCampo3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo3.setText("Campo 3");
        jLStaticCampo3.setEnabled(false);

        jTFCampo3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo3.setEnabled(false);

        jCB1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        jCB1.setEnabled(false);

        jLStaticCB1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB1.setText("CB1");
        jLStaticCB1.setEnabled(false);

        jCB2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        jCB2.setEnabled(false);

        jLStaticCB2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB2.setText("CB2");
        jLStaticCB2.setEnabled(false);

        jLStaticCampo4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo4.setText("Campo 4");
        jLStaticCampo4.setEnabled(false);

        jTFCampo4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo4.setEnabled(false);

        jLStaticCB3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB3.setText("CB3");
        jLStaticCB3.setEnabled(false);

        jCB3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        jCB3.setEnabled(false);

        jLStaticCalendar1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCalendar1.setText("jC1");
        jLStaticCalendar1.setEnabled(false);

        jC1.setEnabled(false);
        jC1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCalendar2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCalendar2.setText("jC2");
        jLStaticCalendar2.setEnabled(false);

        jC2.setEnabled(false);
        jC2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCalendar3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCalendar3.setText("jC3");
        jLStaticCalendar3.setEnabled(false);

        jC3.setEnabled(false);
        jC3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jC4.setEnabled(false);
        jC4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCalendar4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCalendar4.setText("jC4");
        jLStaticCalendar4.setEnabled(false);

        jLStaticCampo7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo7.setText("Campo 7");
        jLStaticCampo7.setEnabled(false);

        jTFCampo7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo7.setEnabled(false);

        jTFCampo6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo6.setEnabled(false);

        jLStaticCampo6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo6.setText("Campo 6");
        jLStaticCampo6.setEnabled(false);

        jLStaticCampo5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo5.setText("Campo 5");
        jLStaticCampo5.setEnabled(false);

        jTFCampo5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo5.setEnabled(false);

        jLOperacionSeleccionada.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLOperacionSeleccionada.setText("Operación sobre un Concepto");
        jLOperacionSeleccionada.setEnabled(false);

        jLStaticEtiqueta2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta2.setText("Etiqueta 2");
        jLStaticEtiqueta2.setEnabled(false);

        jLStaticEtiqueta6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta6.setText("Etiqueta 6");
        jLStaticEtiqueta6.setEnabled(false);

        jLStaticEtiqueta1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta1.setText("Etiqueta 1");
        jLStaticEtiqueta1.setEnabled(false);

        jLStaticEtiqueta4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta4.setText("Etiqueta 4");
        jLStaticEtiqueta4.setEnabled(false);

        jLStaticCampo1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo1.setText("Campo 1");
        jLStaticCampo1.setEnabled(false);

        jTFCampo1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo1.setEnabled(false);

        jLStaticEtiqueta3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta3.setText("Etiqueta 3");
        jLStaticEtiqueta3.setEnabled(false);

        jLStaticEtiqueta8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta8.setText("Etiqueta 8");
        jLStaticEtiqueta8.setEnabled(false);

        jLStaticEtiqueta9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta9.setText("Etiqueta 9");
        jLStaticEtiqueta9.setEnabled(false);

        jLStaticEtiqueta5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta5.setText("Etiqueta 5");
        jLStaticEtiqueta5.setEnabled(false);

        jLStaticEtiqueta7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta7.setText("Etiqueta 7");
        jLStaticEtiqueta7.setEnabled(false);

        jLStaticEtiqueta10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta10.setText("Etiqueta 10");
        jLStaticEtiqueta10.setEnabled(false);

        jLStaticCampo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo2.setText("Campo 2");
        jLStaticCampo2.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(848, 848, 848)
                        .addComponent(jLEstado)
                        .addGap(5, 5, 5)
                        .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLOperacionSeleccionada)
                        .addGap(525, 525, 525)
                        .addComponent(jLStaticCB1)
                        .addGap(4, 4, 4)
                        .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLStaticCampo1)
                        .addGap(12, 12, 12)
                        .addComponent(jTFCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(355, 355, 355)
                        .addComponent(jLStaticCB2)
                        .addGap(4, 4, 4)
                        .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247)
                        .addComponent(jLStaticCalendar1)
                        .addGap(24, 24, 24)
                        .addComponent(jC1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLStaticCampo2)
                        .addGap(12, 12, 12)
                        .addComponent(jTFCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(355, 355, 355)
                        .addComponent(jLStaticCB3)
                        .addGap(4, 4, 4)
                        .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(247, 247, 247)
                        .addComponent(jLStaticCalendar2)
                        .addGap(24, 24, 24)
                        .addComponent(jC2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLStaticCampo3)
                        .addGap(12, 12, 12)
                        .addComponent(jTFCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(805, 805, 805)
                        .addComponent(jLStaticCalendar3)
                        .addGap(24, 24, 24)
                        .addComponent(jC3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLStaticCampo4)
                        .addGap(12, 12, 12)
                        .addComponent(jTFCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(805, 805, 805)
                        .addComponent(jLStaticCalendar4)
                        .addGap(24, 24, 24)
                        .addComponent(jC4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStaticCampo5)
                            .addComponent(jLStaticCampo6)
                            .addComponent(jLStaticCampo7))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFCampo7, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(155, 155, 155)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStaticEtiqueta3)
                            .addComponent(jLStaticEtiqueta8))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStaticEtiqueta1)
                            .addComponent(jLStaticEtiqueta6))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStaticEtiqueta4)
                            .addComponent(jLStaticEtiqueta9))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStaticEtiqueta2)
                            .addComponent(jLStaticEtiqueta7))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStaticEtiqueta5)
                            .addComponent(jLStaticEtiqueta10))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEstado)
                    .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLOperacionSeleccionada)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStaticCB1)
                            .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLStaticCampo1))
                    .addComponent(jTFCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLStaticCB2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLStaticCalendar1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jC1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLStaticCampo2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTFCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLStaticCB3))
                    .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLStaticCalendar2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jC2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLStaticCampo3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jTFCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLStaticCalendar3)
                    .addComponent(jC3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLStaticCampo4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTFCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLStaticCalendar4)
                    .addComponent(jC4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLStaticCampo5)
                        .addGap(17, 17, 17)
                        .addComponent(jLStaticCampo6)
                        .addGap(18, 18, 18)
                        .addComponent(jLStaticCampo7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTFCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jTFCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jTFCampo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLStaticEtiqueta3)
                        .addGap(18, 18, 18)
                        .addComponent(jLStaticEtiqueta8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLStaticEtiqueta1)
                        .addGap(18, 18, 18)
                        .addComponent(jLStaticEtiqueta6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLStaticEtiqueta4)
                        .addGap(18, 18, 18)
                        .addComponent(jLStaticEtiqueta9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLStaticEtiqueta2)
                        .addGap(18, 18, 18)
                        .addComponent(jLStaticEtiqueta7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLStaticEtiqueta5)
                        .addGap(18, 18, 18)
                        .addComponent(jLStaticEtiqueta10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(cabeceraDeVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 1710, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jCBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBConcretarAccion)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(cabeceraDeVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBConcretarAccion)
                    .addComponent(jBCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBConcretarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConcretarAccionActionPerformed
       
        switch ((String)jCBOperacion.getSelectedItem()){
            case "Alta":
                //SE VA A DAR DE ALTA ALGO
                break;
            case "Baja":
                //Se va a dar de baja algo
                break;
            case "Modificacion":
                //Se va a modificar 
                break;
        }
        JOptionPane.showMessageDialog(null, "Operación realizada con exito.");
        deshabilitarTodo();
        limpiarCampos();
        habilitarCamposIniciales();
        
    }//GEN-LAST:event_jBConcretarAccionActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.deshabilitarTodo();
        this.limpiarCampos();
        this.habilitarCamposIniciales();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCBOperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBOperacionItemStateChanged
        if (!jCBOperacion.getSelectedItem().equals("Seleccionar")){
            this.organizarElementos();
            
        }
        
    }//GEN-LAST:event_jCBOperacionItemStateChanged

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        BuscarGenerico unaVentana = new BuscarGenerico(this.organizacion, this, this.trayectoriaActual);
        this.dispose();
    }//GEN-LAST:event_jBBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMGenerico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABMGenerico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private InterfazGrafica.CabeceraDeVentana cabeceraDeVentana;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConcretarAccion;
    private com.toedter.calendar.JDateChooser jC1;
    private com.toedter.calendar.JDateChooser jC2;
    private com.toedter.calendar.JDateChooser jC3;
    private com.toedter.calendar.JDateChooser jC4;
    private javax.swing.JComboBox<String> jCB1;
    private javax.swing.JComboBox<String> jCB2;
    private javax.swing.JComboBox<String> jCB3;
    private javax.swing.JComboBox<String> jCBEstado;
    private javax.swing.JComboBox<String> jCBOperacion;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLOperacionSeleccionada;
    private javax.swing.JLabel jLStaticCB1;
    private javax.swing.JLabel jLStaticCB2;
    private javax.swing.JLabel jLStaticCB3;
    private javax.swing.JLabel jLStaticCalendar1;
    private javax.swing.JLabel jLStaticCalendar2;
    private javax.swing.JLabel jLStaticCalendar3;
    private javax.swing.JLabel jLStaticCalendar4;
    private javax.swing.JLabel jLStaticCampo1;
    private javax.swing.JLabel jLStaticCampo2;
    private javax.swing.JLabel jLStaticCampo3;
    private javax.swing.JLabel jLStaticCampo4;
    private javax.swing.JLabel jLStaticCampo5;
    private javax.swing.JLabel jLStaticCampo6;
    private javax.swing.JLabel jLStaticCampo7;
    private javax.swing.JLabel jLStaticEtiqueta1;
    private javax.swing.JLabel jLStaticEtiqueta10;
    private javax.swing.JLabel jLStaticEtiqueta2;
    private javax.swing.JLabel jLStaticEtiqueta3;
    private javax.swing.JLabel jLStaticEtiqueta4;
    private javax.swing.JLabel jLStaticEtiqueta5;
    private javax.swing.JLabel jLStaticEtiqueta6;
    private javax.swing.JLabel jLStaticEtiqueta7;
    private javax.swing.JLabel jLStaticEtiqueta8;
    private javax.swing.JLabel jLStaticEtiqueta9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFCampo1;
    private javax.swing.JTextField jTFCampo2;
    private javax.swing.JTextField jTFCampo3;
    private javax.swing.JTextField jTFCampo4;
    private javax.swing.JTextField jTFCampo5;
    private javax.swing.JTextField jTFCampo6;
    private javax.swing.JTextField jTFCampo7;
    // End of variables declaration//GEN-END:variables

    private void deshabilitarTodo(){
        //TAMBIEN SE HACEN INVISIBLE LOS ELEMENTOS QUE SEAN NECESARIOS
        jBBuscar.setVisible(false);
        
        jLOperacionSeleccionada.setEnabled(false);
        
        jLStaticCampo1.setEnabled(false);
        jLStaticCampo2.setEnabled(false);
        jLStaticCampo3.setEnabled(false);
        jLStaticCampo4.setEnabled(false);
        jLStaticCampo5.setEnabled(false);
        jLStaticCampo6.setEnabled(false);
        jLStaticCampo7.setEnabled(false);
        
        jTFCampo1.setEnabled(false);
        jTFCampo2.setEnabled(false);
        jTFCampo3.setEnabled(false);
        jTFCampo4.setEnabled(false);
        jTFCampo5.setEnabled(false);
        jTFCampo6.setEnabled(false);
        jTFCampo7.setEnabled(false);
        
        jLEstado.setEnabled(false);
        jLStaticCB1.setEnabled(false);
        jLStaticCB2.setEnabled(false);
        jLStaticCB3.setEnabled(false);
        
        jCBEstado.setEnabled(false);
        jCB1.setEnabled(false);
        jCB2.setEnabled(false);
        jCB3.setEnabled(false);
        
        jLStaticEtiqueta1.setEnabled(false);
        jLStaticEtiqueta2.setEnabled(false);
        jLStaticEtiqueta3.setEnabled(false);
        jLStaticEtiqueta4.setEnabled(false);
        jLStaticEtiqueta5.setEnabled(false);
        jLStaticEtiqueta6.setEnabled(false);
        jLStaticEtiqueta7.setEnabled(false);
        jLStaticEtiqueta8.setEnabled(false);
        jLStaticEtiqueta9.setEnabled(false);
        jLStaticEtiqueta10.setEnabled(false);
        
        jLStaticCalendar1.setEnabled(false);
        jLStaticCalendar2.setEnabled(false);
        jLStaticCalendar3.setEnabled(false);
        jLStaticCalendar4.setEnabled(false);
        
        jC1.setEnabled(false);
        jC2.setEnabled(false);
        jC3.setEnabled(false);
        jC4.setEnabled(false);
        
        jCBOperacion.setEnabled(false);
        jBBuscar.setEnabled(false);
        jBConcretarAccion.setEnabled(false);
        jBCancelar.setEnabled(false);
        
    }
    
    private void limpiarCampos() {
                this.operacionActual = "";
                jLStaticEtiqueta7.setText("Operación:");
                
                jTFCampo1.setText("");
                jTFCampo2.setText("");
                jTFCampo3.setText("");
                jTFCampo4.setText("");
                jTFCampo5.setText("");
                jTFCampo6.setText("");
                jTFCampo7.setText("");
                
                jCB1.setSelectedItem("Seleccionar");
                jCB2.setSelectedItem("Seleccionar");
                jCB3.setSelectedItem("Seleccionar");
                this.unObjetoSeleccionado = null;
    }

    @Override
    public void actualizarUnObjeto(Object unObjeto) {
        Proveedor unProveedor = (Proveedor) unObjeto;
        this.unObjetoSeleccionado = unProveedor;
        jTFCampo1.setText(unProveedor.getRazonSocial());
        jTFCampo2.setText(unProveedor.getCuit());
        jCBEstado.setSelectedItem(unProveedor.getEstado());
        
        organizarElementos();
        jBConcretarAccion.setEnabled(true);
        jBCancelar.setEnabled(true);
        //this.pack();
    }

    private void prepararAlta() {
        this.operacionActual = "Alta";
        jBConcretarAccion.setText("Dar de alta");
        jLOperacionSeleccionada.setText(this.textoAlta);
        
        jLOperacionSeleccionada.setEnabled(true);
        
        jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        
        jTFCampo1.setEnabled(true);
        jTFCampo2.setEnabled(true);
        jTFCampo3.setEnabled(true);
        jTFCampo4.setEnabled(true);
        jTFCampo5.setEnabled(true);
        jTFCampo6.setEnabled(true);
        jTFCampo7.setEnabled(true);
        
        //jLEstado.setEnabled(true); EL ESTADO NO SE ELIGE CUANDO SE DA DE ALTA.
        jLStaticCB1.setEnabled(true);
        jLStaticCB2.setEnabled(true);
        jLStaticCB3.setEnabled(true);
        
        //jCBEstado.setEnabled(true); EL ESTADO NO SE ELIGE CUANDO SE DA DE ALTA.
        jCB1.setEnabled(true);
        jCB2.setEnabled(true);
        jCB3.setEnabled(true);
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        
        jLStaticCalendar1.setEnabled(true);
        jLStaticCalendar2.setEnabled(true);
        jLStaticCalendar3.setEnabled(true);
        jLStaticCalendar4.setEnabled(true);
        
        jC1.setEnabled(true);
        jC2.setEnabled(true);
        jC3.setEnabled(true);
        jC4.setEnabled(true);
        
        jBConcretarAccion.setEnabled(true);
        jBCancelar.setEnabled(true);
        
        
        
    }
    
    private void prepararBaja() {
        this.operacionActual = "Baja";
        
        jBBuscar.setEnabled(true);
        jBBuscar.setVisible(true);
        
        jLOperacionSeleccionada.setText(textoBaja);
        jLOperacionSeleccionada.setEnabled(true);
        
        jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        
        jLEstado.setEnabled(true);
        jLStaticCB1.setEnabled(true);
        jLStaticCB2.setEnabled(true);
        jLStaticCB3.setEnabled(true);
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        
        jLStaticCalendar1.setEnabled(true);
        jLStaticCalendar2.setEnabled(true);
        jLStaticCalendar3.setEnabled(true);
        jLStaticCalendar4.setEnabled(true);
        
        jBCancelar.setEnabled(true);
        
        if (this.unObjetoSeleccionado == null)
            return;
        jBConcretarAccion.setEnabled(true);
        jBConcretarAccion.setText("Dar de baja");
        
    }

    private void prepararModificacion() {
        this.operacionActual = "Modificacion";
        jLOperacionSeleccionada.setText(this.textoModificacion);
        jLOperacionSeleccionada.setEnabled(true);

        jBBuscar.setVisible(true);
        jBBuscar.setEnabled(true);
        jBCancelar.setEnabled(true);
        
        
        if (unObjetoSeleccionado == null)
            return;
        
        
        jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        
        jTFCampo1.setEnabled(true); //SI ALGUN CAMPO NO SE PUDIERA MODIFICAR, (POR EJEMPLO, FECHA DE CREACION, CONCEPTO ASOCIADO, ETC. BORRAR ESTAS LINEAS)
        jTFCampo2.setEnabled(true);
        jTFCampo3.setEnabled(true);
        jTFCampo4.setEnabled(true);
        jTFCampo5.setEnabled(true);
        jTFCampo6.setEnabled(true);
        jTFCampo7.setEnabled(true);
        
        jLEstado.setEnabled(true);
        jLStaticCB1.setEnabled(true);
        jLStaticCB2.setEnabled(true);
        jLStaticCB3.setEnabled(true);
        
        jCBEstado.setEnabled(true);
        jCB1.setEnabled(true);
        jCB2.setEnabled(true);
        jCB3.setEnabled(true);
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        
        jLStaticCalendar1.setEnabled(true);
        jLStaticCalendar2.setEnabled(true);
        jLStaticCalendar3.setEnabled(true);
        jLStaticCalendar4.setEnabled(true);
        
        jC1.setEnabled(true);
        jC2.setEnabled(true);
        jC3.setEnabled(true);
        jC4.setEnabled(true);
        
        jBConcretarAccion.setEnabled(true);
        jBConcretarAccion.setText("Guardar cambios");

    }

    public String getOperacionActual() {
        return operacionActual;
    }

    private void habilitarCamposIniciales() {
        jLabel12.setEnabled(true);
        jCBOperacion.setEnabled(true);
        this.jCBOperacion.setSelectedItem("Seleccionar");
    }
    

}
