/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import LogicaDeNegocio.ExcepcionCargaParametros;
import LogicaDeNegocio.OrdenDeProduccion;
import LogicaDeNegocio.Organizacion;
import Persistencia.ExcepcionPersistencia;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class GestionOrdenesProduccion extends javax.swing.JFrame implements TransferenciaInstancias {
    
    /**
     * Creates new form GestionOrdenesProduccion
     */
    private Organizacion organizacion;
    private JFrame ventanaAnterior;
    private OrdenDeProduccion unaOrdenDeProduccionSeleccionada;
    private String trayectoriaActual;
    private String operacionActual;
    public void setUnaOrdenDeProduccionSeleccionada(OrdenDeProduccion unaOrdenSeleccionada) {
        this.unaOrdenDeProduccionSeleccionada = unaOrdenSeleccionada;
    }
    public GestionOrdenesProduccion() {
        initComponents();
    }



    GestionOrdenesProduccion(Organizacion organizacion, JFrame ventanaAnterior, String trayectoriaAnterior) {
        initComponents();
        this.organizacion = organizacion;
        this.getContentPane().setBackground(ParametrosDeInterfaz.colorFondo);
        setIconImage(new ImageIcon(getClass().getResource(ParametrosDeInterfaz.rutaIcono)).getImage());
        trayectoriaActual = trayectoriaAnterior+" - Gestionar Ordenes de Produccion";
        cabeceraDeVentana.configurarCabecera(ventanaAnterior, this, "Gestion de ordenes de Produccion", this.trayectoriaActual);
        
        
        
        
        this.setVisible(true); 
        jBBuscar.setVisible(false);
        
        this.ventanaAnterior = ventanaAnterior;
    }
    private void organizarElementos(){
        this.deshabilitarTodo();
        switch((String)jCBOperacion.getSelectedItem()){
            case "Registrar":
                prepararAlta();
                break;
            case "Anular":
                prepararBaja();
                break;
            case "Modificacion"://CODIGO OBSOLETO PERO SIGUE ACA POR SI TENGO QUE MODIFICAR ORDENES DE PRODUCCION ALGUN DIA
                prepararModificacion();
                break;
            default:
                limpiarCampos();
                break;
                
        }
        this.pack();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLOperacion = new javax.swing.JLabel();
        jCBUnidadMedida = new javax.swing.JComboBox<>();
        jLEstaticoFechaOrigen = new javax.swing.JLabel();
        jLFechaEntrega = new javax.swing.JLabel();
        jLCantidadAProducir = new javax.swing.JLabel();
        jTFCantidadAProducir = new javax.swing.JTextField();
        jLUnidadMedida = new javax.swing.JLabel();
        jBConcretarAccion = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jCFechaEntrega = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jCBOperacion = new javax.swing.JComboBox<>();
        jBBuscar = new javax.swing.JButton();
        jLEstado = new javax.swing.JLabel();
        jLDescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTADescripcion = new javax.swing.JTextArea();
        cabeceraDeVentana = new InterfazGrafica.CabeceraDeVentana();
        jCBEstado = new javax.swing.JLabel();
        jLFechaOrigen = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jLOperacion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLOperacion.setText("Carga de Orden de Producción");
        jLOperacion.setEnabled(false);

        jCBUnidadMedida.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBUnidadMedida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kilogramo", "Tonelada" }));
        jCBUnidadMedida.setEnabled(false);

        jLEstaticoFechaOrigen.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstaticoFechaOrigen.setText("Fecha de Origen");
        jLEstaticoFechaOrigen.setEnabled(false);

        jLFechaEntrega.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLFechaEntrega.setText("Fecha de Entrega de producto terminado");
        jLFechaEntrega.setEnabled(false);

        jLCantidadAProducir.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLCantidadAProducir.setText("Cantidad a Producir");
        jLCantidadAProducir.setEnabled(false);

        jTFCantidadAProducir.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCantidadAProducir.setText("Ingrese una cantidad");
        jTFCantidadAProducir.setEnabled(false);

        jLUnidadMedida.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLUnidadMedida.setText("Unidad de Medida");
        jLUnidadMedida.setEnabled(false);

        jBConcretarAccion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBConcretarAccion.setText("Aceptar");
        jBConcretarAccion.setEnabled(false);
        jBConcretarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConcretarAccionActionPerformed(evt);
            }
        });

        jBCancelar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jCFechaEntrega.setEnabled(false);
        jCFechaEntrega.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setText("Seleccione una operacion");

        jCBOperacion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Registrar", "Anular" }));
        jCBOperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBOperacionItemStateChanged(evt);
            }
        });

        jBBuscar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscar.setText("Buscar una Orden de Produccion");
        jBBuscar.setEnabled(false);
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLEstado.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstado.setText("Estado");
        jLEstado.setEnabled(false);

        jLDescripcion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLDescripcion.setText("Descripción");
        jLDescripcion.setEnabled(false);

        jTADescripcion.setColumns(20);
        jTADescripcion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTADescripcion.setRows(5);
        jScrollPane1.setViewportView(jTADescripcion);

        jCBEstado.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBEstado.setEnabled(false);

        jLFechaOrigen.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLFechaOrigen.setText("Fecha de Origen");
        jLFechaOrigen.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBConcretarAccion)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cabeceraDeVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLUnidadMedida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLCantidadAProducir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCantidadAProducir, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLFechaEntrega)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLEstaticoFechaOrigen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLFechaOrigen)
                                .addGap(37, 37, 37)
                                .addComponent(jLEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5))
                    .addComponent(jLOperacion)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscar))
                    .addComponent(jLDescripcion)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabeceraDeVentana, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jCBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscar))
                .addGap(18, 18, 18)
                .addComponent(jLOperacion)
                .addGap(18, 18, 18)
                .addComponent(jLDescripcion)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLEstaticoFechaOrigen)
                        .addComponent(jLFechaOrigen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEstado)
                            .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLFechaEntrega)
                    .addComponent(jCFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUnidadMedida)
                    .addComponent(jCBUnidadMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLCantidadAProducir)
                    .addComponent(jTFCantidadAProducir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBConcretarAccion))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConcretarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConcretarAccionActionPerformed
        try {
            switch ((String)jCBOperacion.getSelectedItem()){
                case "Registrar":
                    this.organizacion.registrarOrdenDeProduccion(Calendar.getInstance(),Float.parseFloat(jTFCantidadAProducir.getText()), (String) jCBUnidadMedida.getSelectedItem(), jCFechaEntrega.getCalendar(), jTADescripcion.getText());
                    break;
                case "Anular":
                    this.organizacion.anularOrdenDeProduccion(unaOrdenDeProduccionSeleccionada);
                    break;
                case "Modificacion":
                    
                    break;
            }
            JOptionPane.showMessageDialog(null, "Operacion realizada con exito.");
            limpiarCampos();
        } catch (ExcepcionCargaParametros ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: "+ex.getMessage());
        } catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Por favor, ingrese una Cantidad a Producir en formato valido (Solo numeros y un punto)");
        } catch (ExcepcionPersistencia ex) {
            JOptionPane.showMessageDialog(null, "Error en la Base de datos: "+ex.getMessage());
        }
        
    }//GEN-LAST:event_jBConcretarAccionActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.limpiarCampos();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCBOperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBOperacionItemStateChanged
        if (!jCBOperacion.getSelectedItem().equals("Seleccionar")){
            this.organizarElementos();
            
        }
        
    }//GEN-LAST:event_jCBOperacionItemStateChanged

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        BuscarOrdenDeProduccion unaVentana = new BuscarOrdenDeProduccion(this.organizacion, this, this.trayectoriaActual);
        this.dispose();
    }//GEN-LAST:event_jBBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionOrdenesProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionOrdenesProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionOrdenesProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionOrdenesProduccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionOrdenesProduccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private InterfazGrafica.CabeceraDeVentana cabeceraDeVentana;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConcretarAccion;
    private javax.swing.JLabel jCBEstado;
    private javax.swing.JComboBox<String> jCBOperacion;
    private javax.swing.JComboBox<String> jCBUnidadMedida;
    private com.toedter.calendar.JDateChooser jCFechaEntrega;
    private javax.swing.JLabel jLCantidadAProducir;
    private javax.swing.JLabel jLDescripcion;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLEstaticoFechaOrigen;
    private javax.swing.JLabel jLFechaEntrega;
    private javax.swing.JLabel jLFechaOrigen;
    private javax.swing.JLabel jLOperacion;
    private javax.swing.JLabel jLUnidadMedida;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTADescripcion;
    private javax.swing.JTextField jTFCantidadAProducir;
    // End of variables declaration//GEN-END:variables

    private void deshabilitarTodo(){
        jLOperacion.setEnabled(false);
        
        jLDescripcion.setEnabled(false);
        jLEstado.setEnabled(false);
        jLEstaticoFechaOrigen.setEnabled(false);
        jLFechaEntrega.setEnabled(false);
        jLCantidadAProducir.setEnabled(false);
        jLUnidadMedida.setEnabled(false);
        
        jLEstado.setVisible(false);
        
        jBBuscar.setVisible(false);
        jCBEstado.setVisible(false);
        
        jCBOperacion.setEnabled(false);
        jCBEstado.setEnabled(false);
        jLFechaOrigen.setEnabled(false);
        jCFechaEntrega.setEnabled(false);
        jTFCantidadAProducir.setEnabled(false);
        jCBUnidadMedida.setEnabled(false);
        jTADescripcion.setEnabled(false);
        
        jBConcretarAccion.setEnabled(false);
        jBCancelar.setEnabled(false);
        
    }
    
    private void limpiarCampos() {
                this.operacionActual = "";
                jLOperacion.setText("Operacion:");
                
                jTFCantidadAProducir.setText("");
                jTADescripcion.setText("");
                jLDescripcion.setEnabled(false);
                jLOperacion.setEnabled(false);
                jBBuscar.setVisible(false);
                jLEstaticoFechaOrigen.setEnabled(false);
                jLFechaOrigen.setEnabled(false);
                jLFechaEntrega.setEnabled(false);
                jCFechaEntrega.setEnabled(false);
                jLCantidadAProducir.setEnabled(false);
                jTFCantidadAProducir.setEnabled(false);
                jLUnidadMedida.setEnabled(false);
                jCBUnidadMedida.setEnabled(false);
                jBConcretarAccion.setEnabled(false);
                jBCancelar.setEnabled(false);
                jCBOperacion.setSelectedItem("Seleccionar");
                jLEstado.setEnabled(false);
                jCBEstado.setEnabled(false);
                this.jCBOperacion.setEnabled(true);
                this.unaOrdenDeProduccionSeleccionada = null;
    }

    @Override
    public void actualizarUnObjeto(Object unObjeto) {
        OrdenDeProduccion unaOrdenProduccion = (OrdenDeProduccion) unObjeto;
        this.unaOrdenDeProduccionSeleccionada = unaOrdenProduccion;
        jCBEstado.setText(unaOrdenProduccion.getEstado());
        jTADescripcion.setText(unaOrdenProduccion.getDescripcion());
        jLFechaOrigen.setText(( new SimpleDateFormat( "dd/MM/YYYY" ) ).format( unaOrdenProduccion.getFechaOrigenC().getTime()) );
        jCFechaEntrega.setCalendar(unaOrdenProduccion.getFechaEntregaProductoTerminadoC());
        jCBUnidadMedida.setSelectedItem(unaOrdenProduccion.getUnidadDeMedida());
        jTFCantidadAProducir.setText(""+unaOrdenProduccion.getCantidadAProducir());
        
        organizarElementos();
        jBConcretarAccion.setEnabled(true);
        jBCancelar.setEnabled(true);
        this.pack();
    }

    private void prepararAlta() {
        this.operacionActual = "Alta";
        
        jLEstado.setEnabled(true);
        jLEstaticoFechaOrigen.setEnabled(true);
        jLFechaEntrega.setEnabled(true);
        jLCantidadAProducir.setEnabled(true);
        jLUnidadMedida.setEnabled(true);
        jLDescripcion.setEnabled(true);
        
        
        jCBEstado.setEnabled(true);
        jLFechaOrigen.setEnabled(true);
        jCFechaEntrega.setEnabled(true);
        jTFCantidadAProducir.setEnabled(true);
        jCBUnidadMedida.setEnabled(true);
        jTADescripcion.setEnabled(true);
        
        jBConcretarAccion.setEnabled(true);
        jBCancelar.setEnabled(true);
        
        jLFechaOrigen.setText(( new SimpleDateFormat( "dd-MM-yyyy" ) ).format( Calendar.getInstance().getTime() ));
        
        jBConcretarAccion.setText("Dar de Alta una Orden de Producción");
        jLOperacion.setText("Alta de una Orden de Producción.");
        jLOperacion.setEnabled(true);
    }
    
    private void prepararBaja() {
        this.operacionActual = "Baja";
        jLDescripcion.setEnabled(true);
        jLOperacion.setEnabled(true);
        jLEstado.setEnabled(true);
        jLEstaticoFechaOrigen.setEnabled(true);
        jLFechaEntrega.setEnabled(true);
        jLCantidadAProducir.setEnabled(true);
        jLUnidadMedida.setEnabled(true);
        
        jLEstado.setVisible(true);
        jCBEstado.setVisible(true);
        
        
        jBBuscar.setVisible(true);
        jBBuscar.setEnabled(true);
        jBCancelar.setEnabled(true);
        
        jLOperacion.setText("Baja de una orden de producción.");
        if (this.unaOrdenDeProduccionSeleccionada == null)
            return;
        jBConcretarAccion.setText("Dar de Baja una orden de producción");
    }

    private void prepararModificacion() {
        this.operacionActual = "Modificacion";
        jBBuscar.setVisible(true);
        jBBuscar.setEnabled(true);
        jBCancelar.setEnabled(true);        
        jBConcretarAccion.setText("Guardar cambios");
        if (this.unaOrdenDeProduccionSeleccionada == null)
            return;
        jLOperacion.setEnabled(true);
        jLEstado.setEnabled(true);
        jLEstaticoFechaOrigen.setEnabled(true);
        jLFechaEntrega.setEnabled(true);
        jLCantidadAProducir.setEnabled(true);
        jLUnidadMedida.setEnabled(true);
        
        jLEstado.setVisible(true);
        jCBEstado.setVisible(true);

        jCBEstado.setEnabled(true);
        jLFechaOrigen.setEnabled(true);
        jCFechaEntrega.setEnabled(true);
        jTFCantidadAProducir.setEnabled(true);
        jCBUnidadMedida.setEnabled(true);
        
        jBConcretarAccion.setEnabled(true);
        
    }

    public String getOperacionActual() {
        return operacionActual;
    }
    

}
