/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import LogicaDeNegocio.Organizacion;
import LogicaDeNegocio.Proveedor;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class GestionIngresoMP1backup extends javax.swing.JFrame implements TransferenciaInstancias {
    
    /**
     * Creates new form ABMProveedor
     */
    private Organizacion organizacion;
    private JFrame ventanaAnterior;
    private Proveedor unObjetoSeleccionado;
    private String trayectoriaActual;
    private String operacionActual;
    
    private final String textoAlta = "Registrar ingreso de un Lote";
    private final String textoBaja = "Anular ingreso de un lote";
    private final String textoModificacion = "Modificar un CONCEPTO";
    
    public void setUnObjetoSeleccionado(Proveedor unObjetoSeleccionado) {
        this.unObjetoSeleccionado = unObjetoSeleccionado;
    }
    public GestionIngresoMP1backup() {
        initComponents();
    }



    GestionIngresoMP1backup(Organizacion organizacion, JFrame ventanaAnterior, String trayectoriaAnterior) {
        initComponents();
        this.organizacion = organizacion;
        this.getContentPane().setBackground(ParametrosDeInterfaz.colorFondo);
        setIconImage(new ImageIcon(getClass().getResource(ParametrosDeInterfaz.rutaIcono)).getImage());
        
        trayectoriaActual = trayectoriaAnterior+" - Gestión de ALGUN CONCEPTO";
        cabeceraDeVentana.configurarCabecera(ventanaAnterior, this, "Gestión de ALGUN CONCEPTO", this.trayectoriaActual, organizacion.getUsuarioActivo().getApellido()+", "+organizacion.getUsuarioActivo().getNombre());
        
        

        this.setVisible(true); 
        jBBuscar.setVisible(false);
        
        
        this.ventanaAnterior = ventanaAnterior;
        habilitarCamposIniciales();
    }
    private void organizarElementos(){
        this.deshabilitarTodo();
        switch((String)jCBOperacion.getSelectedItem()){
            case "Alta":
                prepararAlta();
                break;
            case "Baja":
                prepararBaja();
                break;
            case "Modificacion":
                prepararModificacion();
                break;
            default:
                limpiarCampos();
                break;
                
        }
        this.pack();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLStaticEtiqueta7 = new javax.swing.JLabel();
        jBConcretarAccion = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jCBOperacion = new javax.swing.JComboBox<>();
        jBBuscar = new javax.swing.JButton();
        jLEstado = new javax.swing.JLabel();
        jCBEstado = new javax.swing.JComboBox<>();
        cabeceraDeVentana = new InterfazGrafica.CabeceraDeVentana();
        jLStaticCB3 = new javax.swing.JLabel();
        jCB3 = new javax.swing.JComboBox<>();
        jC4 = new com.toedter.calendar.JDateChooser();
        jLStaticCalendar4 = new javax.swing.JLabel();
        jLStaticCampo7 = new javax.swing.JLabel();
        jTFCampo7 = new javax.swing.JTextField();
        jLOperacionSeleccionada = new javax.swing.JLabel();
        jLStaticEtiqueta2 = new javax.swing.JLabel();
        jLStaticEtiqueta1 = new javax.swing.JLabel();
        jLStaticEtiqueta4 = new javax.swing.JLabel();
        jLStaticEtiqueta3 = new javax.swing.JLabel();
        jLStaticEtiqueta8 = new javax.swing.JLabel();
        jLStaticEtiqueta9 = new javax.swing.JLabel();
        jLStaticEtiqueta5 = new javax.swing.JLabel();
        jLStaticEtiqueta10 = new javax.swing.JLabel();
        jBBuscarOrigen = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLStaticEtiqueta6 = new javax.swing.JLabel();
        jLStaticCB1 = new javax.swing.JLabel();
        jCB1 = new javax.swing.JComboBox<>();
        jTFCampo1 = new javax.swing.JTextField();
        jLStaticCampo1 = new javax.swing.JLabel();
        jLStaticCalendar1 = new javax.swing.JLabel();
        jC1 = new com.toedter.calendar.JDateChooser();
        jC2 = new com.github.lgooddatepicker.components.TimePicker();
        jLStaticCalendar2 = new javax.swing.JLabel();
        jLStaticCalendar3 = new javax.swing.JLabel();
        jC3 = new com.github.lgooddatepicker.components.TimePicker();
        jLStaticCB2 = new javax.swing.JLabel();
        jCB2 = new javax.swing.JComboBox<>();
        jLStaticCampo2 = new javax.swing.JLabel();
        jTFCampo2 = new javax.swing.JTextField();
        jLStaticCampo3 = new javax.swing.JLabel();
        jTFCampo3 = new javax.swing.JTextField();
        jLStaticCampo4 = new javax.swing.JLabel();
        jTFCampo4 = new javax.swing.JTextField();
        jLStaticCampo5 = new javax.swing.JLabel();
        jTFCampo5 = new javax.swing.JTextField();
        jLStaticCampo6 = new javax.swing.JLabel();
        jTFCampo6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jLStaticEtiqueta7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta7.setText("Etiqueta 7");
        jLStaticEtiqueta7.setEnabled(false);

        jBConcretarAccion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBConcretarAccion.setText("Aceptar");
        jBConcretarAccion.setEnabled(false);
        jBConcretarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConcretarAccionActionPerformed(evt);
            }
        });

        jBCancelar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setText("Seleccione una operacion");

        jCBOperacion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Alta", "Baja" }));
        jCBOperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBOperacionItemStateChanged(evt);
            }
        });

        jBBuscar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscar.setText("Buscar un Objeto");
        jBBuscar.setEnabled(false);
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLEstado.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstado.setText("Estado");
        jLEstado.setEnabled(false);

        jCBEstado.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Baja" }));
        jCBEstado.setEnabled(false);

        jLStaticCB3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB3.setText("CB3");
        jLStaticCB3.setEnabled(false);

        jCB3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        jCB3.setEnabled(false);

        jC4.setEnabled(false);
        jC4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCalendar4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCalendar4.setText("jC4");
        jLStaticCalendar4.setEnabled(false);

        jLStaticCampo7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo7.setText("Campo 7");
        jLStaticCampo7.setEnabled(false);

        jTFCampo7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo7.setEnabled(false);

        jLOperacionSeleccionada.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLOperacionSeleccionada.setText("Operación sobre un Concepto");
        jLOperacionSeleccionada.setEnabled(false);

        jLStaticEtiqueta2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta2.setText("Equipamiento seleccionado");
        jLStaticEtiqueta2.setEnabled(false);

        jLStaticEtiqueta1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta1.setText("Equipamiento donde se registra el ingreso");
        jLStaticEtiqueta1.setEnabled(false);

        jLStaticEtiqueta4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta4.setText("Báscula asociada");
        jLStaticEtiqueta4.setEnabled(false);

        jLStaticEtiqueta3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta3.setText("un equipamiento");
        jLStaticEtiqueta3.setEnabled(false);

        jLStaticEtiqueta8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta8.setText("Etiqueta 8");
        jLStaticEtiqueta8.setEnabled(false);

        jLStaticEtiqueta9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta9.setText("Etiqueta 9");
        jLStaticEtiqueta9.setEnabled(false);

        jLStaticEtiqueta5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta5.setText("una báscula");
        jLStaticEtiqueta5.setEnabled(false);

        jLStaticEtiqueta10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta10.setText("Etiqueta 10");
        jLStaticEtiqueta10.setEnabled(false);

        jBBuscarOrigen.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscarOrigen.setText("Buscar un Equipamiento");
        jBBuscarOrigen.setEnabled(false);
        jBBuscarOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarOrigenActionPerformed(evt);
            }
        });

        jLStaticEtiqueta6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticEtiqueta6.setText("Detalles de Ticket asociado");
        jLStaticEtiqueta6.setEnabled(false);

        jLStaticCB1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB1.setText("Tipo de unidad de transporte asociado");
        jLStaticCB1.setEnabled(false);

        jCB1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bolsa" }));
        jCB1.setEnabled(false);

        jTFCampo1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo1.setEnabled(false);

        jLStaticCampo1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo1.setText("Cantidad");
        jLStaticCampo1.setEnabled(false);

        jLStaticCalendar1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCalendar1.setText("Fecha de Origen del movimiento");
        jLStaticCalendar1.setEnabled(false);

        jC1.setEnabled(false);
        jC1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jC2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCalendar2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCalendar2.setText("Hora de entrada");
        jLStaticCalendar2.setEnabled(false);

        jLStaticCalendar3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCalendar3.setText("Hora de salida");
        jLStaticCalendar3.setEnabled(false);

        jC3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCB2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCB2.setText("Unidad de medida");
        jLStaticCB2.setEnabled(false);

        jCB2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Kilogramo", "Tonelada" }));
        jCB2.setEnabled(false);

        jLStaticCampo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo2.setText("Peso de entrada");
        jLStaticCampo2.setEnabled(false);

        jTFCampo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo2.setEnabled(false);

        jLStaticCampo3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo3.setText("Peso de salida");
        jLStaticCampo3.setEnabled(false);

        jTFCampo3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo3.setEnabled(false);

        jLStaticCampo4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo4.setText("Nombre del conductor");
        jLStaticCampo4.setEnabled(false);

        jTFCampo4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo4.setEnabled(false);

        jLStaticCampo5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo5.setText("Patente del chasis");
        jLStaticCampo5.setEnabled(false);

        jTFCampo5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo5.setEnabled(false);

        jLStaticCampo6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo6.setText("Patente de acoplado");
        jLStaticCampo6.setEnabled(false);

        jTFCampo6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo6.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLStaticCB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLStaticCampo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCampo1, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLStaticCampo5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFCampo5)
                        .addGap(223, 223, 223))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLStaticEtiqueta6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLStaticCalendar1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLStaticCalendar2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jC2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jC1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCalendar3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jC3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCB2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo3)
                                .addGap(31, 31, 31)
                                .addComponent(jTFCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCampo6)
                                .addGap(11, 11, 11)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLStaticEtiqueta6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCB1)
                    .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticCampo1)
                    .addComponent(jTFCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLStaticCalendar1)
                    .addComponent(jC1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jC2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticCalendar2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLStaticCalendar3)
                    .addComponent(jC3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCB2)
                    .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo2)
                    .addComponent(jTFCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo3)
                    .addComponent(jTFCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo4)
                    .addComponent(jTFCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo5)
                    .addComponent(jTFCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo6)
                    .addComponent(jTFCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cabeceraDeVentana, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBConcretarAccion)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(533, 533, 533)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLStaticCB3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(217, 217, 217)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBBuscar))
                            .addComponent(jLOperacionSeleccionada)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta4)
                                .addGap(18, 18, 18)
                                .addComponent(jLStaticEtiqueta5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBBuscarOrigen))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta2)
                                .addGap(18, 18, 18)
                                .addComponent(jLStaticEtiqueta3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLStaticCampo7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCampo7, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(jLStaticCalendar4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jC4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLStaticEtiqueta8)
                                .addGap(18, 18, 18)
                                .addComponent(jLStaticEtiqueta10)
                                .addGap(260, 260, 260)
                                .addComponent(jLStaticEtiqueta7)
                                .addGap(59, 59, 59)
                                .addComponent(jLStaticEtiqueta9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabeceraDeVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jCBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscar))
                        .addGap(24, 24, 24)
                        .addComponent(jLOperacionSeleccionada)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticEtiqueta1)
                            .addComponent(jBBuscarOrigen))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticEtiqueta2)
                            .addComponent(jLStaticEtiqueta3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticEtiqueta4)
                            .addComponent(jLStaticEtiqueta5))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLEstado)
                            .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLStaticCB3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLStaticEtiqueta8)
                                        .addComponent(jLStaticEtiqueta10))
                                    .addComponent(jLStaticEtiqueta7))
                                .addGap(14, 14, 14))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta9)
                                .addGap(4, 4, 4)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticCampo7)
                            .addComponent(jTFCampo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBCancelar)
                            .addComponent(jBConcretarAccion)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLStaticCalendar4)
                            .addComponent(jC4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBConcretarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConcretarAccionActionPerformed
       
        switch ((String)jCBOperacion.getSelectedItem()){
            case "Alta":
                //SE VA A DAR DE ALTA ALGO
                break;
            case "Baja":
                //Se va a dar de baja algo
                break;
            case "Modificacion":
                //Se va a modificar 
                break;
        }
        JOptionPane.showMessageDialog(null, "Operación realizada con exito.");
        deshabilitarTodo();
        limpiarCampos();
        habilitarCamposIniciales();
        
    }//GEN-LAST:event_jBConcretarAccionActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.deshabilitarTodo();
        this.limpiarCampos();
        this.habilitarCamposIniciales();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCBOperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBOperacionItemStateChanged
        if (!jCBOperacion.getSelectedItem().equals("Seleccionar")){
            this.organizarElementos();
            
        }
        
    }//GEN-LAST:event_jCBOperacionItemStateChanged

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        BuscarGenerico unaVentana = new BuscarGenerico(this.organizacion, this, this.trayectoriaActual);
        this.dispose();
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBBuscarOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarOrigenActionPerformed
        //this.ObjetoABuscar = "Equipamiento Origen";
        BuscarEquipamiento unaVentana = new BuscarEquipamiento(this.organizacion, this, this.trayectoriaActual);

        this.dispose();
    }//GEN-LAST:event_jBBuscarOrigenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionIngresoMP1backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionIngresoMP1backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionIngresoMP1backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionIngresoMP1backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionIngresoMP1backup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private InterfazGrafica.CabeceraDeVentana cabeceraDeVentana;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBBuscarOrigen;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConcretarAccion;
    private com.toedter.calendar.JDateChooser jC1;
    private com.github.lgooddatepicker.components.TimePicker jC2;
    private com.github.lgooddatepicker.components.TimePicker jC3;
    private com.toedter.calendar.JDateChooser jC4;
    private javax.swing.JComboBox<String> jCB1;
    private javax.swing.JComboBox<String> jCB2;
    private javax.swing.JComboBox<String> jCB3;
    private javax.swing.JComboBox<String> jCBEstado;
    private javax.swing.JComboBox<String> jCBOperacion;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLOperacionSeleccionada;
    private javax.swing.JLabel jLStaticCB1;
    private javax.swing.JLabel jLStaticCB2;
    private javax.swing.JLabel jLStaticCB3;
    private javax.swing.JLabel jLStaticCalendar1;
    private javax.swing.JLabel jLStaticCalendar2;
    private javax.swing.JLabel jLStaticCalendar3;
    private javax.swing.JLabel jLStaticCalendar4;
    private javax.swing.JLabel jLStaticCampo1;
    private javax.swing.JLabel jLStaticCampo2;
    private javax.swing.JLabel jLStaticCampo3;
    private javax.swing.JLabel jLStaticCampo4;
    private javax.swing.JLabel jLStaticCampo5;
    private javax.swing.JLabel jLStaticCampo6;
    private javax.swing.JLabel jLStaticCampo7;
    private javax.swing.JLabel jLStaticEtiqueta1;
    private javax.swing.JLabel jLStaticEtiqueta10;
    private javax.swing.JLabel jLStaticEtiqueta2;
    private javax.swing.JLabel jLStaticEtiqueta3;
    private javax.swing.JLabel jLStaticEtiqueta4;
    private javax.swing.JLabel jLStaticEtiqueta5;
    private javax.swing.JLabel jLStaticEtiqueta6;
    private javax.swing.JLabel jLStaticEtiqueta7;
    private javax.swing.JLabel jLStaticEtiqueta8;
    private javax.swing.JLabel jLStaticEtiqueta9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFCampo1;
    private javax.swing.JTextField jTFCampo2;
    private javax.swing.JTextField jTFCampo3;
    private javax.swing.JTextField jTFCampo4;
    private javax.swing.JTextField jTFCampo5;
    private javax.swing.JTextField jTFCampo6;
    private javax.swing.JTextField jTFCampo7;
    // End of variables declaration//GEN-END:variables

    private void deshabilitarTodo(){
        //TAMBIEN SE HACEN INVISIBLE LOS ELEMENTOS QUE SEAN NECESARIOS
        jBBuscar.setVisible(false);
        
        jLOperacionSeleccionada.setEnabled(false);
        
        jLStaticCampo1.setEnabled(false);
        jLStaticCampo2.setEnabled(false);
        jLStaticCampo3.setEnabled(false);
        jLStaticCampo4.setEnabled(false);
        jLStaticCampo5.setEnabled(false);
        jLStaticCampo6.setEnabled(false);
        jLStaticCampo7.setEnabled(false);
        
        jTFCampo1.setEnabled(false);
        jTFCampo2.setEnabled(false);
        jTFCampo3.setEnabled(false);
        jTFCampo4.setEnabled(false);
        jTFCampo5.setEnabled(false);
        jTFCampo6.setEnabled(false);
        jTFCampo7.setEnabled(false);
        
        jLEstado.setEnabled(false);
        jLStaticCB1.setEnabled(false);
        jLStaticCB2.setEnabled(false);
        jLStaticCB3.setEnabled(false);
        
        jCBEstado.setEnabled(false);
        jCB1.setEnabled(false);
        jCB2.setEnabled(false);
        jCB3.setEnabled(false);
        
        jLStaticEtiqueta1.setEnabled(false);
        jLStaticEtiqueta2.setEnabled(false);
        jLStaticEtiqueta3.setEnabled(false);
        jLStaticEtiqueta4.setEnabled(false);
        jLStaticEtiqueta5.setEnabled(false);
        jLStaticEtiqueta6.setEnabled(false);
        jLStaticEtiqueta7.setEnabled(false);
        jLStaticEtiqueta8.setEnabled(false);
        jLStaticEtiqueta9.setEnabled(false);
        jLStaticEtiqueta10.setEnabled(false);
        
        jLStaticCalendar1.setEnabled(false);
        jLStaticCalendar2.setEnabled(false);
        jLStaticCalendar3.setEnabled(false);
        jLStaticCalendar4.setEnabled(false);
        
        jC1.setEnabled(false);
        jC2.setEnabled(false);
        jC3.setEnabled(false);
        jC4.setEnabled(false);
        
        jCBOperacion.setEnabled(false);
        jBBuscar.setEnabled(false);
        jBConcretarAccion.setEnabled(false);
        jBCancelar.setEnabled(false);
        
    }
    
    private void limpiarCampos() {
                this.operacionActual = "";
                jLStaticEtiqueta7.setText("Operación:");
                
                jTFCampo1.setText("");
                jTFCampo2.setText("");
                jTFCampo3.setText("");
                jTFCampo4.setText("");
                jTFCampo5.setText("");
                jTFCampo6.setText("");
                jTFCampo7.setText("");
                
                jCB1.setSelectedItem("Seleccionar");
                jCB2.setSelectedItem("Seleccionar");
                jCB3.setSelectedItem("Seleccionar");
                this.unObjetoSeleccionado = null;
    }

    @Override
    public void actualizarUnObjeto(Object UnObjeto) {
        Proveedor unProveedor = (Proveedor) UnObjeto;
        this.unObjetoSeleccionado = unProveedor;
        jTFCampo1.setText(unProveedor.getRazonSocial());
        jTFCampo2.setText(unProveedor.getCuit());
        jCBEstado.setSelectedItem(unProveedor.getEstado());
        
        organizarElementos();
        jBConcretarAccion.setEnabled(true);
        jBCancelar.setEnabled(true);
        this.pack();
    }

    private void prepararAlta() {
        this.operacionActual = "Alta";
        jBConcretarAccion.setText("Dar de alta");
        jLOperacionSeleccionada.setText(this.textoAlta);
        
        jLOperacionSeleccionada.setEnabled(true);
        
        jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        
        jTFCampo1.setEnabled(true);
        jTFCampo2.setEnabled(true);
        jTFCampo3.setEnabled(true);
        jTFCampo4.setEnabled(true);
        jTFCampo5.setEnabled(true);
        jTFCampo6.setEnabled(true);
        jTFCampo7.setEnabled(true);
        
        //jLEstado.setEnabled(true); EL ESTADO NO SE ELIGE CUANDO SE DA DE ALTA.
        jLStaticCB1.setEnabled(true);
        jLStaticCB2.setEnabled(true);
        jLStaticCB3.setEnabled(true);
        
        //jCBEstado.setEnabled(true); EL ESTADO NO SE ELIGE CUANDO SE DA DE ALTA.
        jCB1.setEnabled(true);
        jCB2.setEnabled(true);
        jCB3.setEnabled(true);
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        
        jLStaticCalendar1.setEnabled(true);
        jLStaticCalendar2.setEnabled(true);
        jLStaticCalendar3.setEnabled(true);
        jLStaticCalendar4.setEnabled(true);
        
        jC1.setEnabled(true);
        jC2.setEnabled(true);
        jC3.setEnabled(true);
        jC4.setEnabled(true);
        
        jBConcretarAccion.setEnabled(true);
        jBCancelar.setEnabled(true);
        
        
        
    }
    
    private void prepararBaja() {
        this.operacionActual = "Baja";
        
        jBBuscar.setEnabled(true);
        jBBuscar.setVisible(true);
        
        jLOperacionSeleccionada.setText(textoBaja);
        jLOperacionSeleccionada.setEnabled(true);
        
        jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        
        jLEstado.setEnabled(true);
        jLStaticCB1.setEnabled(true);
        jLStaticCB2.setEnabled(true);
        jLStaticCB3.setEnabled(true);
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        
        jLStaticCalendar1.setEnabled(true);
        jLStaticCalendar2.setEnabled(true);
        jLStaticCalendar3.setEnabled(true);
        jLStaticCalendar4.setEnabled(true);
        
        jBCancelar.setEnabled(true);
        
        if (this.unObjetoSeleccionado == null)
            return;
        jBConcretarAccion.setEnabled(true);
        jBConcretarAccion.setText("Dar de baja");
        
    }

    private void prepararModificacion() {
        this.operacionActual = "Modificacion";
        jLOperacionSeleccionada.setText(this.textoModificacion);
        jLOperacionSeleccionada.setEnabled(true);

        jBBuscar.setVisible(true);
        jBBuscar.setEnabled(true);
        jBCancelar.setEnabled(true);
        
        
        if (unObjetoSeleccionado == null)
            return;
        
        
        jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        
        jTFCampo1.setEnabled(true); //SI ALGUN CAMPO NO SE PUDIERA MODIFICAR, (POR EJEMPLO, FECHA DE CREACION, CONCEPTO ASOCIADO, ETC. BORRAR ESTAS LINEAS)
        jTFCampo2.setEnabled(true);
        jTFCampo3.setEnabled(true);
        jTFCampo4.setEnabled(true);
        jTFCampo5.setEnabled(true);
        jTFCampo6.setEnabled(true);
        jTFCampo7.setEnabled(true);
        
        jLEstado.setEnabled(true);
        jLStaticCB1.setEnabled(true);
        jLStaticCB2.setEnabled(true);
        jLStaticCB3.setEnabled(true);
        
        jCBEstado.setEnabled(true);
        jCB1.setEnabled(true);
        jCB2.setEnabled(true);
        jCB3.setEnabled(true);
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        
        jLStaticCalendar1.setEnabled(true);
        jLStaticCalendar2.setEnabled(true);
        jLStaticCalendar3.setEnabled(true);
        jLStaticCalendar4.setEnabled(true);
        
        jC1.setEnabled(true);
        jC2.setEnabled(true);
        jC3.setEnabled(true);
        jC4.setEnabled(true);
        
        jBConcretarAccion.setEnabled(true);
        jBConcretarAccion.setText("Guardar cambios");

    }

    public String getOperacionActual() {
        return operacionActual;
    }

    private void habilitarCamposIniciales() {
        jLabel12.setEnabled(true);
        jCBOperacion.setEnabled(true);
        this.jCBOperacion.setSelectedItem("Seleccionar");
    }
    

}
