/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica;

import LogicaDeNegocio.Bascula;
import LogicaDeNegocio.Equipamiento;
import LogicaDeNegocio.ExcepcionCargaParametros;
import LogicaDeNegocio.OrdenDeCompra;
import LogicaDeNegocio.Organizacion;
import LogicaDeNegocio.Proveedor;
import Persistencia.ExcepcionPersistencia;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class GestionIngresoMP extends javax.swing.JFrame implements TransferenciaInstancias {
    
    /**
     * Creates new form ABMProveedor
     */
    private Organizacion organizacion;
    private JFrame ventanaAnterior;
    private OrdenDeCompra unaOrdenDeCompraSeleccionada;
    private Equipamiento unEquipamientoSeleccionado;
    private Proveedor unProveedorDeTransporteSeleccionado;

    private String trayectoriaActual;
    private String operacionActual;
    
    private final String textoAlta = "Registrar ingreso de un Lote";
    private final String textoBaja = "Anular ingreso de un lote";
    private final String textoModificacion = "Modificar un CONCEPTO";
    
    
    public void setUnaOrdenDeCompraSeleccionada(OrdenDeCompra unaOrdenDeCompraSeleccionada) {
        this.unaOrdenDeCompraSeleccionada = unaOrdenDeCompraSeleccionada;
    }
    public GestionIngresoMP() {
        initComponents();
    }



    GestionIngresoMP(Organizacion organizacion, JFrame ventanaAnterior, String trayectoriaAnterior) {
        initComponents();
        this.organizacion = organizacion;
        this.getContentPane().setBackground(ParametrosDeInterfaz.colorFondo);
        setIconImage(new ImageIcon(getClass().getResource(ParametrosDeInterfaz.rutaIcono)).getImage());
        
        trayectoriaActual = trayectoriaAnterior+" - Gestión de ingresos de materia prima";
        cabeceraDeVentana.configurarCabecera(ventanaAnterior, this, "Gestión de ingresos de materia prima", this.trayectoriaActual, organizacion.getUsuarioActivo().getApellido()+", "+organizacion.getUsuarioActivo().getNombre());
        
        

        this.setVisible(true); 
        jBBuscar.setVisible(false);
        
        
        this.ventanaAnterior = ventanaAnterior;
        habilitarCamposIniciales();
    }
    private void organizarElementos(){
        this.deshabilitarTodo();
        switch((String)jCBOperacion.getSelectedItem()){
            case "Alta":
                prepararAlta();
                break;
            case "Baja":
                prepararBaja();
                break;
            case "Modificacion":
                prepararModificacion();
                break;
            default:
                limpiarCampos();
                break;
                
        }
        this.pack();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBConcretarAccion = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jCBOperacion = new javax.swing.JComboBox<>();
        jBBuscar = new javax.swing.JButton();
        cabeceraDeVentana = new InterfazGrafica.CabeceraDeVentana();
        jLOperacionSeleccionada = new javax.swing.JLabel();
        jLStaticEtiqueta2 = new javax.swing.JLabel();
        jLStaticEtiqueta1 = new javax.swing.JLabel();
        jLStaticEtiqueta4 = new javax.swing.JLabel();
        jLStaticEtiqueta3 = new javax.swing.JLabel();
        jLStaticEtiqueta5 = new javax.swing.JLabel();
        jBBuscarDestino = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLStaticEtiqueta6 = new javax.swing.JLabel();
        jLStaticCB1 = new javax.swing.JLabel();
        jCB1 = new javax.swing.JComboBox<>();
        jTFCampo1 = new javax.swing.JTextField();
        jLStaticCampo1 = new javax.swing.JLabel();
        jLStaticCalendar1 = new javax.swing.JLabel();
        jC1 = new com.toedter.calendar.JDateChooser();
        jC2 = new com.github.lgooddatepicker.components.TimePicker();
        jLStaticCalendar2 = new javax.swing.JLabel();
        jLStaticCalendar3 = new javax.swing.JLabel();
        jC3 = new com.github.lgooddatepicker.components.TimePicker();
        jLStaticCB2 = new javax.swing.JLabel();
        jCB2 = new javax.swing.JComboBox<>();
        jLStaticCampo2 = new javax.swing.JLabel();
        jTFCampo2 = new javax.swing.JTextField();
        jLStaticCampo3 = new javax.swing.JLabel();
        jTFCampo3 = new javax.swing.JTextField();
        jLStaticCampo4 = new javax.swing.JLabel();
        jTFCampo4 = new javax.swing.JTextField();
        jLStaticCampo5 = new javax.swing.JLabel();
        jTFCampo5 = new javax.swing.JTextField();
        jLStaticCampo6 = new javax.swing.JLabel();
        jTFCampo6 = new javax.swing.JTextField();
        jLStaticCampo7 = new javax.swing.JLabel();
        jTFCampo7 = new javax.swing.JTextField();
        jLStaticCampo8 = new javax.swing.JLabel();
        jTFCampo8 = new javax.swing.JTextField();
        jLStaticCampo9 = new javax.swing.JLabel();
        jTFCampo9 = new javax.swing.JTextField();
        jLStaticEtiqueta10 = new javax.swing.JLabel();
        jLStaticEtiqueta11 = new javax.swing.JLabel();
        jBBuscarOrdenCompra = new javax.swing.JButton();
        jLStaticEtiqueta12 = new javax.swing.JLabel();
        jLStaticEtiqueta8 = new javax.swing.JLabel();
        jLStaticEtiqueta9 = new javax.swing.JLabel();
        jLStaticEtiqueta7 = new javax.swing.JLabel();
        jBBuscarProveedor = new javax.swing.JButton();
        jLStaticEtiqueta13 = new javax.swing.JLabel();
        jLStaticEtiqueta14 = new javax.swing.JLabel();
        jLStaticEtiqueta15 = new javax.swing.JLabel();
        jLStaticEtiqueta16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jBConcretarAccion.setText("Aceptar");
        jBConcretarAccion.setEnabled(false);
        jBConcretarAccion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBConcretarAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConcretarAccionActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.setEnabled(false);
        jBCancelar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jLabel12.setText("Seleccione una operacion");
        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jCBOperacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Alta", "Baja" }));
        jCBOperacion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBOperacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBOperacionItemStateChanged(evt);
            }
        });

        jBBuscar.setText("Buscar un ingreso");
        jBBuscar.setEnabled(false);
        jBBuscar.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jLOperacionSeleccionada.setText("Operación sobre un Concepto");
        jLOperacionSeleccionada.setEnabled(false);
        jLOperacionSeleccionada.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta2.setText("Equipamiento seleccionado");
        jLStaticEtiqueta2.setEnabled(false);
        jLStaticEtiqueta2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta1.setText("Equipamiento donde se registra el ingreso");
        jLStaticEtiqueta1.setEnabled(false);
        jLStaticEtiqueta1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta4.setText("Báscula asociada");
        jLStaticEtiqueta4.setEnabled(false);
        jLStaticEtiqueta4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta3.setText("un equipamiento");
        jLStaticEtiqueta3.setEnabled(false);
        jLStaticEtiqueta3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta5.setText("una báscula");
        jLStaticEtiqueta5.setEnabled(false);
        jLStaticEtiqueta5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jBBuscarDestino.setText("Buscar un Equipamiento");
        jBBuscarDestino.setEnabled(false);
        jBBuscarDestino.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarDestinoActionPerformed(evt);
            }
        });

        jLStaticEtiqueta6.setText("Detalles de Ticket asociado");
        jLStaticEtiqueta6.setEnabled(false);
        jLStaticEtiqueta6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCB1.setText("Tipo de unidad de transporte asociado");
        jLStaticCB1.setEnabled(false);
        jLStaticCB1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jCB1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bolsa" }));
        jCB1.setEnabled(false);
        jCB1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo1.setEnabled(false);
        jTFCampo1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCampo1.setText("Cantidad");
        jLStaticCampo1.setEnabled(false);
        jLStaticCampo1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCalendar1.setText("Fecha de Origen del movimiento");
        jLStaticCalendar1.setEnabled(false);
        jLStaticCalendar1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jC1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jC1.setEnabled(false);

        jC2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCalendar2.setText("Hora de entrada");
        jLStaticCalendar2.setEnabled(false);
        jLStaticCalendar2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCalendar3.setText("Hora de salida");
        jLStaticCalendar3.setEnabled(false);
        jLStaticCalendar3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jC3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCB2.setText("Unidad de medida");
        jLStaticCB2.setEnabled(false);
        jLStaticCB2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jCB2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Kilogramo", "Tonelada" }));
        jCB2.setEnabled(false);
        jCB2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCampo2.setText("Peso de entrada");
        jLStaticCampo2.setEnabled(false);
        jLStaticCampo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo2.setEnabled(false);
        jTFCampo2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCampo3.setText("Peso de salida");
        jLStaticCampo3.setEnabled(false);
        jLStaticCampo3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo3.setEnabled(false);
        jTFCampo3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCampo4.setText("Nombre del conductor");
        jLStaticCampo4.setEnabled(false);
        jLStaticCampo4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo4.setEnabled(false);
        jTFCampo4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCampo5.setText("Patente del chasis");
        jLStaticCampo5.setEnabled(false);
        jLStaticCampo5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo5.setEnabled(false);
        jTFCampo5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCampo6.setText("Patente de acoplado");
        jLStaticCampo6.setEnabled(false);
        jLStaticCampo6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo6.setEnabled(false);
        jTFCampo6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCampo7.setText("Numero de Precinto");
        jLStaticCampo7.setEnabled(false);
        jLStaticCampo7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTFCampo7.setEnabled(false);
        jTFCampo7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticCampo8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo8.setText("Numero de Hoja de ruta");
        jLStaticCampo8.setEnabled(false);

        jTFCampo8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo8.setEnabled(false);

        jLStaticCampo9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLStaticCampo9.setText("Numero de remito");
        jLStaticCampo9.setEnabled(false);

        jTFCampo9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jTFCampo9.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLStaticCampo5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFCampo5)
                        .addGap(223, 223, 223))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLStaticCB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLStaticCampo1)
                        .addGap(36, 36, 36)
                        .addComponent(jTFCampo1, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCampo6))
                            .addComponent(jLStaticEtiqueta6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLStaticCalendar1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLStaticCalendar2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jC2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jC1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCalendar3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jC3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCB2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo3)
                                .addGap(31, 31, 31)
                                .addComponent(jTFCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTFCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCampo7, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCampo8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLStaticCampo9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFCampo9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLStaticEtiqueta6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCB1)
                    .addComponent(jCB1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticCampo1)
                    .addComponent(jTFCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLStaticCalendar1)
                    .addComponent(jC1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jC2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLStaticCalendar2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLStaticCalendar3)
                    .addComponent(jC3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCB2)
                    .addComponent(jCB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo2)
                    .addComponent(jTFCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo3)
                    .addComponent(jTFCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo4)
                    .addComponent(jTFCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo5)
                    .addComponent(jTFCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo6)
                    .addComponent(jTFCampo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo7)
                    .addComponent(jTFCampo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo8)
                    .addComponent(jTFCampo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLStaticCampo9)
                    .addComponent(jTFCampo9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jLStaticEtiqueta10.setText("Orden de compra seleccionada:");
        jLStaticEtiqueta10.setEnabled(false);
        jLStaticEtiqueta10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta11.setText("Orden de Compra asociada");
        jLStaticEtiqueta11.setEnabled(false);
        jLStaticEtiqueta11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jBBuscarOrdenCompra.setText("Buscar una orden de compra");
        jBBuscarOrdenCompra.setEnabled(false);
        jBBuscarOrdenCompra.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscarOrdenCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarOrdenCompraActionPerformed(evt);
            }
        });

        jLStaticEtiqueta12.setText("una orden de compra");
        jLStaticEtiqueta12.setEnabled(false);
        jLStaticEtiqueta12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta8.setText("Proveedor seleccionado");
        jLStaticEtiqueta8.setEnabled(false);
        jLStaticEtiqueta8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta9.setText("un proveedor");
        jLStaticEtiqueta9.setEnabled(false);
        jLStaticEtiqueta9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta7.setText("Proveedor de Servicio de Transporte");
        jLStaticEtiqueta7.setEnabled(false);
        jLStaticEtiqueta7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jBBuscarProveedor.setText("Buscar un Proveedor");
        jBBuscarProveedor.setEnabled(false);
        jBBuscarProveedor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jBBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarProveedorActionPerformed(evt);
            }
        });

        jLStaticEtiqueta13.setText("Proveedor de transporte seleccionado");
        jLStaticEtiqueta13.setEnabled(false);
        jLStaticEtiqueta13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta14.setText("un proveedor de transporte");
        jLStaticEtiqueta14.setEnabled(false);
        jLStaticEtiqueta14.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta15.setText("Etiqueta a utilizar en el lote ingresado:");
        jLStaticEtiqueta15.setEnabled(false);
        jLStaticEtiqueta15.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLStaticEtiqueta16.setText("etiqueta");
        jLStaticEtiqueta16.setEnabled(false);
        jLStaticEtiqueta16.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cabeceraDeVentana, javax.swing.GroupLayout.DEFAULT_SIZE, 1785, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBConcretarAccion)
                        .addGap(18, 18, 18)
                        .addComponent(jBCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLOperacionSeleccionada)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta4)
                                .addGap(18, 18, 18)
                                .addComponent(jLStaticEtiqueta5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta2)
                                .addGap(18, 18, 18)
                                .addComponent(jLStaticEtiqueta3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLStaticEtiqueta12))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBBuscarOrdenCompra))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta8)
                                .addGap(18, 18, 18)
                                .addComponent(jLStaticEtiqueta9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBBuscarDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBBuscarProveedor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLStaticEtiqueta14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLStaticEtiqueta15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLStaticEtiqueta16))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBBuscar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cabeceraDeVentana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jCBOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(jLOperacionSeleccionada)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticEtiqueta11)
                            .addComponent(jBBuscarOrdenCompra))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticEtiqueta10)
                            .addComponent(jLStaticEtiqueta12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticEtiqueta8)
                            .addComponent(jLStaticEtiqueta9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticEtiqueta1)
                            .addComponent(jBBuscarDestino))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticEtiqueta2)
                            .addComponent(jLStaticEtiqueta3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticEtiqueta4)
                            .addComponent(jLStaticEtiqueta5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticEtiqueta7)
                            .addComponent(jBBuscarProveedor))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticEtiqueta13)
                            .addComponent(jLStaticEtiqueta14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLStaticEtiqueta15)
                            .addComponent(jLStaticEtiqueta16))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBConcretarAccion))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBConcretarAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConcretarAccionActionPerformed
       
        try {
            switch ((String)jCBOperacion.getSelectedItem()){
                case "Alta":
                    LocalTime unHorarioEntrada = jC2.getTime();
                    LocalTime unHorarioSalida = jC3.getTime();
                    organizacion.registrarIngresoMateriaPrima(jC1.getCalendar(), unHorarioEntrada, unHorarioSalida, (String) jCB1.getSelectedItem(), jTFCampo1.getText(), (String) jCB2.getSelectedItem(), jTFCampo2.getText(), jTFCampo3.getText(), jTFCampo8.getText(), jTFCampo9.getText(), jTFCampo7.getText(), jTFCampo4.getText(), jTFCampo5.getText(), jTFCampo6.getText(), unEquipamientoSeleccionado, unaOrdenDeCompraSeleccionada, unProveedorDeTransporteSeleccionado);
                    
                    break;
                case "Baja":
                    //Se va a dar de baja algo
                    break;
                case "Modificacion":
                    //Se va a modificar
                    break;
            }
            JOptionPane.showMessageDialog(null, "Operación realizada con exito.");
            deshabilitarTodo();
            limpiarCampos();
            habilitarCamposIniciales();
        } catch (ExcepcionCargaParametros ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en la base de datos: "+ ex.getMessage());
        } catch (ExcepcionPersistencia ex) {
            JOptionPane.showMessageDialog(null, "Error en la Persistencia: "+ ex.getMessage());
        }
        
    }//GEN-LAST:event_jBConcretarAccionActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        this.deshabilitarTodo();
        this.limpiarCampos();
        this.habilitarCamposIniciales();
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jCBOperacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBOperacionItemStateChanged
        if (!jCBOperacion.getSelectedItem().equals("Seleccionar")){
            this.organizarElementos();
            
        }
        
    }//GEN-LAST:event_jCBOperacionItemStateChanged

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        BuscarGenerico unaVentana = new BuscarGenerico(this.organizacion, this, this.trayectoriaActual);
        this.dispose();
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBBuscarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarDestinoActionPerformed
        //this.ObjetoABuscar = "Equipamiento Origen";
        BuscarEquipamiento unaVentana = new BuscarEquipamiento(this.organizacion, this, this.trayectoriaActual);
        this.dispose();
    }//GEN-LAST:event_jBBuscarDestinoActionPerformed

    private void jBBuscarOrdenCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarOrdenCompraActionPerformed
        BuscarOrdenCompra unaVentana = new BuscarOrdenCompra(this.organizacion, this, this.trayectoriaActual);
        this.dispose();
    }//GEN-LAST:event_jBBuscarOrdenCompraActionPerformed

    private void jBBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarProveedorActionPerformed
        BuscarProveedor unaVentana = new BuscarProveedor(this.organizacion, this, this.trayectoriaActual);
        this.dispose();
    }//GEN-LAST:event_jBBuscarProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionIngresoMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionIngresoMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionIngresoMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionIngresoMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionIngresoMP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private InterfazGrafica.CabeceraDeVentana cabeceraDeVentana;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBBuscarDestino;
    private javax.swing.JButton jBBuscarOrdenCompra;
    private javax.swing.JButton jBBuscarProveedor;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBConcretarAccion;
    private com.toedter.calendar.JDateChooser jC1;
    private com.github.lgooddatepicker.components.TimePicker jC2;
    private com.github.lgooddatepicker.components.TimePicker jC3;
    private javax.swing.JComboBox<String> jCB1;
    private javax.swing.JComboBox<String> jCB2;
    private javax.swing.JComboBox<String> jCBOperacion;
    private javax.swing.JLabel jLOperacionSeleccionada;
    private javax.swing.JLabel jLStaticCB1;
    private javax.swing.JLabel jLStaticCB2;
    private javax.swing.JLabel jLStaticCalendar1;
    private javax.swing.JLabel jLStaticCalendar2;
    private javax.swing.JLabel jLStaticCalendar3;
    private javax.swing.JLabel jLStaticCampo1;
    private javax.swing.JLabel jLStaticCampo2;
    private javax.swing.JLabel jLStaticCampo3;
    private javax.swing.JLabel jLStaticCampo4;
    private javax.swing.JLabel jLStaticCampo5;
    private javax.swing.JLabel jLStaticCampo6;
    private javax.swing.JLabel jLStaticCampo7;
    private javax.swing.JLabel jLStaticCampo8;
    private javax.swing.JLabel jLStaticCampo9;
    private javax.swing.JLabel jLStaticEtiqueta1;
    private javax.swing.JLabel jLStaticEtiqueta10;
    private javax.swing.JLabel jLStaticEtiqueta11;
    private javax.swing.JLabel jLStaticEtiqueta12;
    private javax.swing.JLabel jLStaticEtiqueta13;
    private javax.swing.JLabel jLStaticEtiqueta14;
    private javax.swing.JLabel jLStaticEtiqueta15;
    private javax.swing.JLabel jLStaticEtiqueta16;
    private javax.swing.JLabel jLStaticEtiqueta2;
    private javax.swing.JLabel jLStaticEtiqueta3;
    private javax.swing.JLabel jLStaticEtiqueta4;
    private javax.swing.JLabel jLStaticEtiqueta5;
    private javax.swing.JLabel jLStaticEtiqueta6;
    private javax.swing.JLabel jLStaticEtiqueta7;
    private javax.swing.JLabel jLStaticEtiqueta8;
    private javax.swing.JLabel jLStaticEtiqueta9;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFCampo1;
    private javax.swing.JTextField jTFCampo2;
    private javax.swing.JTextField jTFCampo3;
    private javax.swing.JTextField jTFCampo4;
    private javax.swing.JTextField jTFCampo5;
    private javax.swing.JTextField jTFCampo6;
    private javax.swing.JTextField jTFCampo7;
    private javax.swing.JTextField jTFCampo8;
    private javax.swing.JTextField jTFCampo9;
    // End of variables declaration//GEN-END:variables

    private void deshabilitarTodo(){
        //TAMBIEN SE HACEN INVISIBLE LOS ELEMENTOS QUE SEAN NECESARIOS
        jBBuscar.setVisible(false);
        
        jLOperacionSeleccionada.setEnabled(false);
        
        jLStaticCampo1.setEnabled(false);
        jLStaticCampo2.setEnabled(false);
        jLStaticCampo3.setEnabled(false);
        jLStaticCampo4.setEnabled(false);
        jLStaticCampo5.setEnabled(false);
        jLStaticCampo6.setEnabled(false);
        jLStaticCampo7.setEnabled(false);
        jLStaticCampo8.setEnabled(false);
        jLStaticCampo9.setEnabled(false);
        
        jTFCampo1.setEnabled(false);
        jTFCampo2.setEnabled(false);
        jTFCampo3.setEnabled(false);
        jTFCampo4.setEnabled(false);
        jTFCampo5.setEnabled(false);
        jTFCampo6.setEnabled(false);
        jTFCampo7.setEnabled(false);
        jTFCampo8.setEnabled(false);
        jTFCampo9.setEnabled(false);
        
        jLStaticCB1.setEnabled(false);
        jLStaticCB2.setEnabled(false);
        
        jCB1.setEnabled(false);
        jCB2.setEnabled(false);
        
        jLStaticEtiqueta1.setEnabled(false);
        jLStaticEtiqueta2.setEnabled(false);
        jLStaticEtiqueta3.setEnabled(false);
        jLStaticEtiqueta4.setEnabled(false);
        jLStaticEtiqueta5.setEnabled(false);
        jLStaticEtiqueta6.setEnabled(false);
        jLStaticEtiqueta7.setEnabled(false);
        jLStaticEtiqueta8.setEnabled(false);
        jLStaticEtiqueta9.setEnabled(false);
        jLStaticEtiqueta10.setEnabled(false);
        jLStaticEtiqueta11.setEnabled(false);
        jLStaticEtiqueta12.setEnabled(false);
        jLStaticEtiqueta13.setEnabled(false);
        jLStaticEtiqueta14.setEnabled(false);
        jLStaticEtiqueta15.setEnabled(false);
        jLStaticEtiqueta16.setEnabled(false);
        
        jLStaticCalendar1.setEnabled(false);
        jLStaticCalendar2.setEnabled(false);
        jLStaticCalendar3.setEnabled(false);
        
        jC1.setEnabled(false);
        jC2.setEnabled(false);
        jC3.setEnabled(false);
        
        jCBOperacion.setEnabled(false);
        jBBuscar.setEnabled(false);
        
        jBBuscarOrdenCompra.setEnabled(false);
        jBBuscarDestino.setEnabled(false);
        jBBuscarProveedor.setEnabled(false);
        
        jBConcretarAccion.setEnabled(false);
        jBCancelar.setEnabled(false);
        
        
        

    }
    
    private void limpiarCampos() {
                this.operacionActual = "";
                jLStaticEtiqueta7.setText("Operación:");
                
                jTFCampo1.setText("");
                jTFCampo2.setText("");
                jTFCampo3.setText("");
                jTFCampo4.setText("");
                jTFCampo5.setText("");
                jTFCampo6.setText("");
                jTFCampo7.setText("");
                
                jCB1.setSelectedItem("Seleccionar");
                jCB2.setSelectedItem("Seleccionar");
                this.unaOrdenDeCompraSeleccionada = null;
    }

    @Override
    public void actualizarUnObjeto(Object unObjeto) {
        if (unObjeto instanceof OrdenDeCompra){
            try {
                unaOrdenDeCompraSeleccionada = (OrdenDeCompra) unObjeto;
                if (!unaOrdenDeCompraSeleccionada.poseeProveedorAsociado())
                    throw new ExcepcionCargaParametros("No se puede seleccionar una orden de compra sin proveedor asociado.");
                exhibirOrdenDeCompraYProveedor();
            } catch (ExcepcionCargaParametros ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
                return;
            }
        }
        if (unObjeto instanceof Equipamiento){
            try {
                if (unObjeto instanceof Bascula)
                    throw new ExcepcionCargaParametros("No se puede seleccionar una bascula como destino");
                this.unEquipamientoSeleccionado = (Equipamiento) unObjeto;
                exhibirEquipamiento();
            } catch (ExcepcionCargaParametros ex) {
                JOptionPane.showMessageDialog(null,ex.getMessage());
                return;
            }
        }
        if (unObjeto instanceof Proveedor){
            unProveedorDeTransporteSeleccionado = (Proveedor) unObjeto;
            exhibirProveedorDeTransporte();
        }        
        
        
        
        organizarElementos();
        jBConcretarAccion.setEnabled(true);
        jBCancelar.setEnabled(true);
        this.pack();
    }

    private void prepararAlta() {
        this.operacionActual = "Alta";
        jBConcretarAccion.setText("Dar de alta");
        jLOperacionSeleccionada.setText(this.textoAlta);
        
        jC1.setCalendar(Calendar.getInstance());
        
        
        jBBuscarOrdenCompra.setEnabled(true);
        jBBuscarDestino.setEnabled(true);
        jBBuscarProveedor.setEnabled(true);
        
        jLOperacionSeleccionada.setEnabled(true);
        
        jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        jLStaticCampo8.setEnabled(true);
        jLStaticCampo9.setEnabled(true);
        
        jTFCampo1.setEnabled(true);
        jTFCampo2.setEnabled(true);
        jTFCampo3.setEnabled(true);
        jTFCampo4.setEnabled(true);
        jTFCampo5.setEnabled(true);
        jTFCampo6.setEnabled(true);
        jTFCampo7.setEnabled(true);
        jTFCampo8.setEnabled(true);
        jTFCampo9.setEnabled(true);
        
        //jLEstado.setEnabled(true); EL ESTADO NO SE ELIGE CUANDO SE DA DE ALTA.
        jLStaticCB1.setEnabled(true);
        jLStaticCB2.setEnabled(true);
        
        //jCBEstado.setEnabled(true); EL ESTADO NO SE ELIGE CUANDO SE DA DE ALTA.
        jCB1.setEnabled(true);
        jCB2.setEnabled(true);
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        jLStaticEtiqueta11.setEnabled(true);
        jLStaticEtiqueta12.setEnabled(true);
        jLStaticEtiqueta13.setEnabled(true);
        jLStaticEtiqueta14.setEnabled(true);
        jLStaticEtiqueta15.setEnabled(true);
        jLStaticEtiqueta16.setEnabled(true);
        

        
        jLStaticCalendar1.setEnabled(true);
        jLStaticCalendar2.setEnabled(true);
        jLStaticCalendar3.setEnabled(true);
        
        //jC1.setEnabled(true); NO se puede editar la fecha de origen de un ingreso de materia prima.
        jC2.setEnabled(true);
        jC3.setEnabled(true);
        
        jBBuscarOrdenCompra.setEnabled(true);
        jBBuscarDestino.setEnabled(true);
        jBBuscarProveedor.setEnabled(true);
        
        jBConcretarAccion.setEnabled(true);
        jBCancelar.setEnabled(true);
        
        
        
    }
    
    private void prepararBaja() {
        this.operacionActual = "Baja";
        
        jBBuscar.setEnabled(true);
        jBBuscar.setVisible(true);
        
        jLOperacionSeleccionada.setText(textoBaja);
        jLOperacionSeleccionada.setEnabled(true);
        
        jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        jLStaticCampo8.setEnabled(true);
        jLStaticCampo9.setEnabled(true);
        
        jLStaticCB1.setEnabled(true);
        jLStaticCB2.setEnabled(true);
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        jLStaticEtiqueta11.setEnabled(true);
        jLStaticEtiqueta12.setEnabled(true);
        jLStaticEtiqueta13.setEnabled(true);
        jLStaticEtiqueta14.setEnabled(true);
        jLStaticEtiqueta15.setEnabled(true);
        jLStaticEtiqueta16.setEnabled(true);
        
        jLStaticCalendar1.setEnabled(true);
        jLStaticCalendar2.setEnabled(true);
        jLStaticCalendar3.setEnabled(true);
        
        jBCancelar.setEnabled(true);
        
        if (this.unaOrdenDeCompraSeleccionada == null)
            return;
        jBConcretarAccion.setEnabled(true);
        jBConcretarAccion.setText("Dar de baja");
        
    }

    private void prepararModificacion() {
        this.operacionActual = "Modificacion";
        jLOperacionSeleccionada.setText(this.textoModificacion);
        jLOperacionSeleccionada.setEnabled(true);

        jBBuscar.setVisible(true);
        jBBuscar.setEnabled(true);
        jBCancelar.setEnabled(true);
        
        
        if (unaOrdenDeCompraSeleccionada == null)
            return;
        
        
        jLStaticCampo1.setEnabled(true);
        jLStaticCampo2.setEnabled(true);
        jLStaticCampo3.setEnabled(true);
        jLStaticCampo4.setEnabled(true);
        jLStaticCampo5.setEnabled(true);
        jLStaticCampo6.setEnabled(true);
        jLStaticCampo7.setEnabled(true);
        jLStaticCampo8.setEnabled(true);
        jLStaticCampo9.setEnabled(true);
        
        jTFCampo1.setEnabled(true); //SI ALGUN CAMPO NO SE PUDIERA MODIFICAR, (POR EJEMPLO, FECHA DE CREACION, CONCEPTO ASOCIADO, ETC. BORRAR ESTAS LINEAS)
        jTFCampo2.setEnabled(true);
        jTFCampo3.setEnabled(true);
        jTFCampo4.setEnabled(true);
        jTFCampo5.setEnabled(true);
        jTFCampo6.setEnabled(true);
        jTFCampo7.setEnabled(true);
        jTFCampo8.setEnabled(true);
        jTFCampo9.setEnabled(true);
        
        jLStaticCB1.setEnabled(true);
        jLStaticCB2.setEnabled(true);
        
        jCB1.setEnabled(true);
        jCB2.setEnabled(true);
        
        jLStaticEtiqueta1.setEnabled(true);
        jLStaticEtiqueta2.setEnabled(true);
        jLStaticEtiqueta3.setEnabled(true);
        jLStaticEtiqueta4.setEnabled(true);
        jLStaticEtiqueta5.setEnabled(true);
        jLStaticEtiqueta6.setEnabled(true);
        jLStaticEtiqueta7.setEnabled(true);
        jLStaticEtiqueta8.setEnabled(true);
        jLStaticEtiqueta9.setEnabled(true);
        jLStaticEtiqueta10.setEnabled(true);
        jLStaticEtiqueta11.setEnabled(true);
        jLStaticEtiqueta12.setEnabled(true);
        jLStaticEtiqueta13.setEnabled(true);
        jLStaticEtiqueta14.setEnabled(true);
        jLStaticEtiqueta15.setEnabled(true);
        jLStaticEtiqueta16.setEnabled(true);
        
        jLStaticCalendar1.setEnabled(true);
        jLStaticCalendar2.setEnabled(true);
        jLStaticCalendar3.setEnabled(true);
        
        jC1.setEnabled(true);
        jC2.setEnabled(true);
        jC3.setEnabled(true);
        
        jBConcretarAccion.setEnabled(true);
        jBConcretarAccion.setText("Guardar cambios");

    }

    public String getOperacionActual() {
        return operacionActual;
    }

    private void habilitarCamposIniciales() {
        jLabel12.setEnabled(true);
        jCBOperacion.setEnabled(true);
        this.jCBOperacion.setSelectedItem("Seleccionar");
    }


    private void exhibirOrdenDeCompraYProveedor() {
        try {
            jLStaticEtiqueta12.setText(unaOrdenDeCompraSeleccionada.getId()+", "+unaOrdenDeCompraSeleccionada.getCantidadRestanteARecibir()+" "+unaOrdenDeCompraSeleccionada.getUnidadDeMedida()+"(s).");
            jLStaticEtiqueta9.setText(unaOrdenDeCompraSeleccionada.getProveedorAsociado().getRazonSocial()+" (Cuit: "+unaOrdenDeCompraSeleccionada.getProveedorAsociado().getCuit()+")");
        } catch (ExcepcionCargaParametros ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void exhibirEquipamiento() {
        jLStaticEtiqueta3.setText(unEquipamientoSeleccionado.getNombre());
        jLStaticEtiqueta5.setText(unEquipamientoSeleccionado.getBasculaAsociada().getNombre());
    }

    private void exhibirProveedorDeTransporte() {
        if (unProveedorDeTransporteSeleccionado.getRazonSocial().length()>30)
            jLStaticEtiqueta14.setText(unProveedorDeTransporteSeleccionado.getRazonSocial().substring(0, 30)+"...");
        else
            jLStaticEtiqueta14.setText(unProveedorDeTransporteSeleccionado.getRazonSocial());
    }
    

}
