/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfazGrafica.Estadisticas;

import InterfazGrafica.Busqueda.BuscarCriterioAnalisisLaboratorio;
import InterfazGrafica.Busqueda.BuscarEquipamiento;
import InterfazGrafica.Busqueda.BuscarLote;
import InterfazGrafica.Busqueda.BuscarOrdenCompra;
import InterfazGrafica.Busqueda.BuscarOrdenDeProduccion;
import InterfazGrafica.Paneles.Panel;
import InterfazGrafica.Paneles.PanelGestionAnalisisLaboratorio;
import InterfazGrafica.TransferenciaInstancias;
import LogicaDeNegocio.AnalisisLaboratorio;
import LogicaDeNegocio.CriterioAnalisisLaboratorio;
import LogicaDeNegocio.Equipamiento;
import LogicaDeNegocio.ExcepcionCargaParametros;
import LogicaDeNegocio.Lote;
import LogicaDeNegocio.OrdenDeCompra;
import LogicaDeNegocio.OrdenDeProduccion;
import LogicaDeNegocio.Organizacion;
import Reportes.GeneradorDeReportes;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import net.sf.jasperreports.engine.JRException;
import org.jfree.chart.ChartPanel;

/**
 *
 * @author usuario
 */
public class SubPanelEstadisticaLaboratorio extends Panel implements TransferenciaInstancias {

    /**
     * Creates new form subPanelEstadisticaProveedores
     */
    
    private Lote unLoteSeleccionado;
    private CriterioAnalisisLaboratorio unCriterioSeleccionado;
    private OrdenDeProduccion unaOrdenDeProduccion;
    private Equipamiento unLaboratorio;
    private OrdenDeCompra unaOrdenDeCompra;
    private AnalisisLaboratorio unObjetoSeleccionado;
    
    public static final String[] criterios = PanelGestionAnalisisLaboratorio.criterios;
    
    public SubPanelEstadisticaLaboratorio(JFrame ventanaContenedora, String trayectoriaActual, Organizacion unaOrganizacion, String tituloReporte) {
        super(ventanaContenedora, trayectoriaActual, unaOrganizacion, criterios, tituloReporte);
        initComponents();
        jPanel6.setLayout(new BoxLayout(jPanel6, BoxLayout.Y_AXIS));
        configurarOpcionesCensables();
        this.setVisible(true);

        
        
    }

    public SubPanelEstadisticaLaboratorio() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        botonCriterio8 = new javax.swing.JButton();
        jLEstaticoCriterio7 = new javax.swing.JLabel();
        datoCriterio2 = new javax.swing.JTextField();
        botonCriterio7 = new javax.swing.JButton();
        botonCriterio9 = new javax.swing.JButton();
        jCBCriterio4 = new javax.swing.JCheckBox();
        jCBCriterio1 = new javax.swing.JCheckBox();
        jCBCriterio2 = new javax.swing.JCheckBox();
        jCBCriterio8 = new javax.swing.JCheckBox();
        jCBCriterio9 = new javax.swing.JCheckBox();
        jLEstaticoCriterio4 = new javax.swing.JLabel();
        jCBCriterio7 = new javax.swing.JCheckBox();
        jLCriterio8 = new javax.swing.JLabel();
        jLEstaticoCriterio9 = new javax.swing.JLabel();
        botonCriterio4 = new javax.swing.JButton();
        jLEstaticoCriterio8 = new javax.swing.JLabel();
        jLCriterio4 = new javax.swing.JLabel();
        jLEstaticoCriterio1 = new javax.swing.JLabel();
        botonCriterio1 = new javax.swing.JButton();
        jLCriterio7 = new javax.swing.JLabel();
        jLCriterio9 = new javax.swing.JLabel();
        jLCriterio1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLEstatico1Criterio6 = new javax.swing.JLabel();
        dato1Criterio6 = new com.toedter.calendar.JDateChooser();
        jLEstatico2Criterio6 = new javax.swing.JLabel();
        dato2Criterio6 = new com.toedter.calendar.JDateChooser();
        datoCriterio5 = new javax.swing.JComboBox<>();
        jCBCriterio6 = new javax.swing.JCheckBox();
        jCBCriterio3 = new javax.swing.JCheckBox();
        jCBCriterio5 = new javax.swing.JCheckBox();
        datoCriterio3 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jCBCriterio10 = new javax.swing.JCheckBox();
        dato1Criterio10 = new javax.swing.JRadioButton();
        dato2Criterio10 = new javax.swing.JRadioButton();
        jLEstaticoCriterio2 = new javax.swing.JLabel();
        datoCriterio4 = new javax.swing.JComboBox<>();
        jCBCriterio11 = new javax.swing.JCheckBox();
        datoCriterio11 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLEstaticoTamanoMuestra = new javax.swing.JLabel();
        jLEstaticoTamanoMuestra1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Estadísticas generales de análisis de laboratorio");

        jPanel1.setBackground(new java.awt.Color(201, 201, 201));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 624, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Distribución de frecuencia de los atributos de los análisis de laboratorio");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Consulta de análisis de laboratorio");

        jButton1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton1.setText("Generar estadística");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonCriterio8.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        botonCriterio8.setText("Buscar un laboratorio");
        botonCriterio8.setEnabled(false);
        botonCriterio8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCriterio8ActionPerformed(evt);
            }
        });

        jLEstaticoCriterio7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstaticoCriterio7.setText("Orden de produccion seleccionada:");

        datoCriterio2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        datoCriterio2.setText("Ingrese un comentario");
        datoCriterio2.setEnabled(false);

        botonCriterio7.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        botonCriterio7.setText("Buscar una Orden de produccion");
        botonCriterio7.setEnabled(false);
        botonCriterio7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCriterio7ActionPerformed(evt);
            }
        });

        botonCriterio9.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        botonCriterio9.setText("Buscar una orden de compra");
        botonCriterio9.setEnabled(false);
        botonCriterio9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCriterio9ActionPerformed(evt);
            }
        });

        jCBCriterio4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBCriterio4.setText("Criterio implicado");
        jCBCriterio4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCriterio4ItemStateChanged(evt);
            }
        });

        jCBCriterio1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBCriterio1.setText("Lote implicado");
        jCBCriterio1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Assets/CheckTic.png"))); // NOI18N
        jCBCriterio1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCriterio1ItemStateChanged(evt);
            }
        });

        jCBCriterio2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBCriterio2.setText("Comentario");
        jCBCriterio2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCriterio2ItemStateChanged(evt);
            }
        });

        jCBCriterio8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBCriterio8.setText("Laboratorio implicado");
        jCBCriterio8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCriterio8ItemStateChanged(evt);
            }
        });

        jCBCriterio9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBCriterio9.setText("Orden de compra implicada");
        jCBCriterio9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCriterio9ItemStateChanged(evt);
            }
        });

        jLEstaticoCriterio4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstaticoCriterio4.setText("Criterio de análisis seleccionado:");

        jCBCriterio7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBCriterio7.setText("Orden de produccion implicada");
        jCBCriterio7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCriterio7ItemStateChanged(evt);
            }
        });

        jLCriterio8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLEstaticoCriterio9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstaticoCriterio9.setText("Orden de compra seleccionada");

        botonCriterio4.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        botonCriterio4.setText("Buscar un criterio de analisis");
        botonCriterio4.setEnabled(false);
        botonCriterio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCriterio4ActionPerformed(evt);
            }
        });

        jLEstaticoCriterio8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstaticoCriterio8.setText("Laboratorio seleccionado");

        jLCriterio4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLEstaticoCriterio1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstaticoCriterio1.setText("Lote seleccionado:");

        botonCriterio1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        botonCriterio1.setText("Buscar un lote");
        botonCriterio1.setEnabled(false);
        botonCriterio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCriterio1ActionPerformed(evt);
            }
        });

        jLCriterio7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLCriterio9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLCriterio1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCriterio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLEstaticoCriterio1)
                        .addGap(18, 18, 18)
                        .addComponent(jLCriterio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jCBCriterio9)
                                .addGap(18, 18, 18)
                                .addComponent(botonCriterio9))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLEstaticoCriterio7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLCriterio7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jCBCriterio8)
                                    .addGap(18, 18, 18)
                                    .addComponent(botonCriterio8))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jCBCriterio7)
                                    .addGap(18, 18, 18)
                                    .addComponent(botonCriterio7))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLEstaticoCriterio8)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLCriterio8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLEstaticoCriterio9)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLCriterio9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jCBCriterio1)
                                .addGap(18, 18, 18)
                                .addComponent(botonCriterio1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jCBCriterio4)
                                .addGap(18, 18, 18)
                                .addComponent(botonCriterio4))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jCBCriterio2)
                                .addGap(18, 18, 18)
                                .addComponent(datoCriterio2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLEstaticoCriterio4))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCriterio1)
                    .addComponent(botonCriterio1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLCriterio1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEstaticoCriterio1))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCriterio2)
                    .addComponent(datoCriterio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCBCriterio4)
                    .addComponent(botonCriterio4))
                .addGap(18, 18, 18)
                .addComponent(jLEstaticoCriterio4)
                .addGap(18, 18, 18)
                .addComponent(jLCriterio4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(botonCriterio7)
                            .addComponent(jCBCriterio7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLCriterio7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLEstaticoCriterio7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBCriterio8)
                            .addComponent(botonCriterio8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLEstaticoCriterio8)
                            .addComponent(jLCriterio8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(botonCriterio9)
                            .addComponent(jCBCriterio9))
                        .addGap(18, 18, 18)
                        .addComponent(jLEstaticoCriterio9))
                    .addComponent(jLCriterio9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLEstatico1Criterio6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstatico1Criterio6.setText("Desde");
        jLEstatico1Criterio6.setEnabled(false);

        dato1Criterio6.setEnabled(false);
        dato1Criterio6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jLEstatico2Criterio6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstatico2Criterio6.setText("Hasta");
        jLEstatico2Criterio6.setEnabled(false);

        dato2Criterio6.setEnabled(false);
        dato2Criterio6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        datoCriterio5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        datoCriterio5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Regular", "Anulado" }));
        datoCriterio5.setEnabled(false);

        jCBCriterio6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBCriterio6.setText("Fecha de origen");
        jCBCriterio6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCriterio6ItemStateChanged(evt);
            }
        });

        jCBCriterio3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBCriterio3.setText("Tipo de lote");
        jCBCriterio3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCriterio3ItemStateChanged(evt);
            }
        });

        jCBCriterio5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBCriterio5.setText("Estado");
        jCBCriterio5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/InterfazGrafica/Assets/CheckTic.png"))); // NOI18N
        jCBCriterio5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCriterio5ItemStateChanged(evt);
            }
        });

        datoCriterio3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        datoCriterio3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "YCV", "YCE", "YM" }));
        datoCriterio3.setEnabled(false);

        jCBCriterio10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBCriterio10.setText("Posee lote asociado");
        jCBCriterio10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCriterio10ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(dato1Criterio10);
        dato1Criterio10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        dato1Criterio10.setText("Si");
        dato1Criterio10.setEnabled(false);
        dato1Criterio10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dato1Criterio10ItemStateChanged(evt);
            }
        });

        buttonGroup1.add(dato2Criterio10);
        dato2Criterio10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        dato2Criterio10.setText("No");
        dato2Criterio10.setEnabled(false);
        dato2Criterio10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dato2Criterio10ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCBCriterio10)
                .addGap(18, 18, 18)
                .addComponent(dato1Criterio10)
                .addGap(18, 18, 18)
                .addComponent(dato2Criterio10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dato1Criterio10)
                        .addComponent(dato2Criterio10))
                    .addComponent(jCBCriterio10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLEstaticoCriterio2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstaticoCriterio2.setText("Dato a censar");

        datoCriterio4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jCBCriterio11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jCBCriterio11.setText("Conclusión");
        jCBCriterio11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBCriterio11ItemStateChanged(evt);
            }
        });

        datoCriterio11.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        datoCriterio11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "APROBADO", "RECHAZADO" }));
        datoCriterio11.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jCBCriterio11)
                                .addGap(18, 18, 18)
                                .addComponent(datoCriterio11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jCBCriterio3)
                                .addGap(18, 18, 18)
                                .addComponent(datoCriterio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jCBCriterio5)
                                .addGap(18, 18, 18)
                                .addComponent(datoCriterio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jCBCriterio6)
                                .addGap(18, 18, 18)
                                .addComponent(jLEstatico1Criterio6)
                                .addGap(6, 6, 6)
                                .addComponent(dato1Criterio6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLEstatico2Criterio6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dato2Criterio6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLEstaticoCriterio2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(datoCriterio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCriterio3)
                    .addComponent(datoCriterio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBCriterio5)
                    .addComponent(datoCriterio5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jCBCriterio6)
                    .addComponent(jLEstatico1Criterio6)
                    .addComponent(dato1Criterio6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEstatico2Criterio6)
                    .addComponent(dato2Criterio6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCBCriterio11)
                    .addComponent(datoCriterio11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEstaticoCriterio2)
                    .addComponent(datoCriterio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jButton2.setText("Generar reporte");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        jLEstaticoTamanoMuestra.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstaticoTamanoMuestra.setText("Tamaño de la población que cumple los criterios seleccionados");

        jLEstaticoTamanoMuestra1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLEstaticoTamanoMuestra1.setText("##");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLEstaticoTamanoMuestra)
                        .addGap(18, 18, 18)
                        .addComponent(jLEstaticoTamanoMuestra1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLEstaticoTamanoMuestra)
                    .addComponent(jLEstaticoTamanoMuestra1))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ArrayList listaFiltradaAnalisis = null;
            generarObjetos();
            listaFiltradaAnalisis = (this.organizacion.filtrarGenerico(criterios, this.criteriosSeleccionados, this.objetosAsociadosACriterios, (Map) organizacion.getAnalisisLaboratorio()));
            ArrayList listaObservada = Organizacion.desmenuzarAnalisis(listaFiltradaAnalisis, (String) datoCriterio4.getSelectedItem());
            jLEstaticoTamanoMuestra1.setText(""+listaObservada.size());
            Estadistica.agregarChartPanel(jPanel1, Estadistica.generarHistogramaPorcentajes(listaObservada, "Distribución de frecuencia de "+datoCriterio4.getSelectedItem(), 1.5f));
            generarBarras(listaFiltradaAnalisis);
            generarTortaAprobadosYDesaprobados(listaFiltradaAnalisis);
        } catch (ExcepcionCargaParametros ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botonCriterio8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCriterio8ActionPerformed
        BuscarEquipamiento ventana = new BuscarEquipamiento(this.organizacion, ventanaContenedora, this.trayectoriaActual);
        ventanaContenedora.dispose();
    }//GEN-LAST:event_botonCriterio8ActionPerformed

    private void botonCriterio7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCriterio7ActionPerformed
        BuscarOrdenDeProduccion unaVentana = new BuscarOrdenDeProduccion(this.organizacion, ventanaContenedora, this.trayectoriaActual);
        ventanaContenedora.dispose();
    }//GEN-LAST:event_botonCriterio7ActionPerformed

    private void botonCriterio9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCriterio9ActionPerformed
        BuscarOrdenCompra ventana = new BuscarOrdenCompra(this.organizacion, ventanaContenedora, this.trayectoriaActual);
        ventanaContenedora.dispose();
    }//GEN-LAST:event_botonCriterio9ActionPerformed

    private void jCBCriterio4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCriterio4ItemStateChanged
        botonCriterio4.setEnabled(jCBCriterio4.isSelected());
        jLEstaticoCriterio4.setEnabled(jCBCriterio4.isSelected());
        jLCriterio4.setEnabled(jCBCriterio4.isSelected());
        asignarCriterio(3, (JCheckBox) evt.getSource());
    }//GEN-LAST:event_jCBCriterio4ItemStateChanged

    private void jCBCriterio1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCriterio1ItemStateChanged
        botonCriterio1.setEnabled(jCBCriterio1.isSelected());
        jLEstaticoCriterio1.setEnabled(jCBCriterio1.isSelected());
        jLCriterio1.setEnabled(jCBCriterio1.isSelected());
        asignarCriterio(0, (JCheckBox) evt.getSource());
    }//GEN-LAST:event_jCBCriterio1ItemStateChanged

    private void jCBCriterio2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCriterio2ItemStateChanged
        datoCriterio2.setEnabled(jCBCriterio2.isSelected());
        asignarCriterio(1, (JCheckBox) evt.getSource());
    }//GEN-LAST:event_jCBCriterio2ItemStateChanged

    private void jCBCriterio8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCriterio8ItemStateChanged
        botonCriterio8.setEnabled(jCBCriterio8.isSelected());
        jLEstaticoCriterio8.setEnabled(jCBCriterio8.isSelected());
        jLCriterio8.setEnabled(jCBCriterio8.isSelected());
        asignarCriterio(7, (JCheckBox) evt.getSource());
    }//GEN-LAST:event_jCBCriterio8ItemStateChanged

    private void jCBCriterio9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCriterio9ItemStateChanged
        botonCriterio9.setEnabled(jCBCriterio9.isSelected());
        jLEstaticoCriterio9.setEnabled(jCBCriterio9.isSelected());
        jLCriterio9.setEnabled(jCBCriterio9.isSelected());
        asignarCriterio(8, (JCheckBox) evt.getSource());
    }//GEN-LAST:event_jCBCriterio9ItemStateChanged

    private void jCBCriterio7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCriterio7ItemStateChanged
        botonCriterio7.setEnabled(jCBCriterio7.isSelected());
        jLEstaticoCriterio7.setEnabled(jCBCriterio7.isSelected());
        jLCriterio7.setEnabled(jCBCriterio7.isSelected());
        asignarCriterio(6, (JCheckBox) evt.getSource());
    }//GEN-LAST:event_jCBCriterio7ItemStateChanged

    private void botonCriterio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCriterio4ActionPerformed
        BuscarCriterioAnalisisLaboratorio ventana = new BuscarCriterioAnalisisLaboratorio(this.organizacion, ventanaContenedora, this.trayectoriaActual);
        ventanaContenedora.dispose();
    }//GEN-LAST:event_botonCriterio4ActionPerformed

    private void botonCriterio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCriterio1ActionPerformed
        BuscarLote unaVentana = new BuscarLote(organizacion, ventanaContenedora, trayectoriaActual, null);
        ventanaContenedora.dispose();
    }//GEN-LAST:event_botonCriterio1ActionPerformed

    private void jCBCriterio6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCriterio6ItemStateChanged
        jLEstatico1Criterio6.setEnabled(jCBCriterio6.isSelected());
        dato1Criterio6.setEnabled(jCBCriterio6.isSelected());
        jLEstatico2Criterio6.setEnabled(jCBCriterio6.isSelected());
        dato2Criterio6.setEnabled(jCBCriterio6.isSelected());
        asignarCriterio(5, (JCheckBox) evt.getSource());
    }//GEN-LAST:event_jCBCriterio6ItemStateChanged

    private void jCBCriterio3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCriterio3ItemStateChanged
        datoCriterio3.setEnabled(jCBCriterio3.isSelected());
        asignarCriterio(2, (JCheckBox) evt.getSource());
    }//GEN-LAST:event_jCBCriterio3ItemStateChanged

    private void jCBCriterio5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCriterio5ItemStateChanged
        datoCriterio5.setEnabled(jCBCriterio5.isSelected());
        asignarCriterio(4, (JCheckBox) evt.getSource());
    }//GEN-LAST:event_jCBCriterio5ItemStateChanged

    private void jCBCriterio10ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCriterio10ItemStateChanged
        dato1Criterio10.setEnabled(((JCheckBox)evt.getItemSelectable()).isSelected());
        dato2Criterio10.setEnabled(((JCheckBox)evt.getItemSelectable()).isSelected());
        asignarCriterio(9, (JCheckBox) evt.getSource());
    }//GEN-LAST:event_jCBCriterio10ItemStateChanged

    private void dato1Criterio10ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dato1Criterio10ItemStateChanged
        if (((JRadioButton)evt.getItemSelectable()).isSelected()){
            asignarObjetoACriterio(9, true);
        }
    }//GEN-LAST:event_dato1Criterio10ItemStateChanged

    private void dato2Criterio10ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dato2Criterio10ItemStateChanged
        if (((JRadioButton)evt.getItemSelectable()).isSelected()){
            asignarObjetoACriterio(9, false);
        }
    }//GEN-LAST:event_dato2Criterio10ItemStateChanged

    private void jCBCriterio11ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBCriterio11ItemStateChanged
        datoCriterio11.setEnabled(((JCheckBox)evt.getItemSelectable()).isSelected());
        asignarCriterio(10, (JCheckBox) evt.getSource());
    }//GEN-LAST:event_jCBCriterio11ItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            ArrayList listaFiltradaAnalisis = null;
            generarObjetos();
            listaFiltradaAnalisis = (this.organizacion.filtrarGenerico(criterios, this.criteriosSeleccionados, this.objetosAsociadosACriterios, (Map) organizacion.getAnalisisLaboratorio()));
            Map<String, String> criterios = getCriterios();
            ArrayList listaTuplas = Estadistica.generarTuplasEstadisticaAnalisisLaboratorio(listaFiltradaAnalisis);
            GeneradorDeReportes.generarReporteGenericoEstadistica("Analisis de laboratorio", criteriosSeleccionados, criterios, listaTuplas, organizacion.getUsuarioActivo().getApellido()+", "+organizacion.getUsuarioActivo().getNombre());
        } catch (ExcepcionCargaParametros ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    @Override
    protected void generarObjetos() {
        asignarObjetoACriterio(1, datoCriterio2.getText());
        asignarObjetoACriterio(2, datoCriterio3.getSelectedItem());
        asignarObjetoACriterio(4, datoCriterio5.getSelectedItem());
        asignarObjetoACriterio(5, generarListaFecha(dato1Criterio6.getCalendar(), dato2Criterio6.getCalendar()));
        asignarObjetoACriterio(10, datoCriterio11.getSelectedItem());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCriterio1;
    private javax.swing.JButton botonCriterio4;
    private javax.swing.JButton botonCriterio7;
    private javax.swing.JButton botonCriterio8;
    private javax.swing.JButton botonCriterio9;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton dato1Criterio10;
    private com.toedter.calendar.JDateChooser dato1Criterio6;
    private javax.swing.JRadioButton dato2Criterio10;
    private com.toedter.calendar.JDateChooser dato2Criterio6;
    private javax.swing.JComboBox<String> datoCriterio11;
    private javax.swing.JTextField datoCriterio2;
    private javax.swing.JComboBox<String> datoCriterio3;
    private javax.swing.JComboBox<String> datoCriterio4;
    private javax.swing.JComboBox<String> datoCriterio5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCBCriterio1;
    private javax.swing.JCheckBox jCBCriterio10;
    private javax.swing.JCheckBox jCBCriterio11;
    private javax.swing.JCheckBox jCBCriterio2;
    private javax.swing.JCheckBox jCBCriterio3;
    private javax.swing.JCheckBox jCBCriterio4;
    private javax.swing.JCheckBox jCBCriterio5;
    private javax.swing.JCheckBox jCBCriterio6;
    private javax.swing.JCheckBox jCBCriterio7;
    private javax.swing.JCheckBox jCBCriterio8;
    private javax.swing.JCheckBox jCBCriterio9;
    private javax.swing.JLabel jLCriterio1;
    private javax.swing.JLabel jLCriterio4;
    private javax.swing.JLabel jLCriterio7;
    private javax.swing.JLabel jLCriterio8;
    private javax.swing.JLabel jLCriterio9;
    private javax.swing.JLabel jLEstatico1Criterio6;
    private javax.swing.JLabel jLEstatico2Criterio6;
    private javax.swing.JLabel jLEstaticoCriterio1;
    private javax.swing.JLabel jLEstaticoCriterio2;
    private javax.swing.JLabel jLEstaticoCriterio4;
    private javax.swing.JLabel jLEstaticoCriterio7;
    private javax.swing.JLabel jLEstaticoCriterio8;
    private javax.swing.JLabel jLEstaticoCriterio9;
    private javax.swing.JLabel jLEstaticoTamanoMuestra;
    private javax.swing.JLabel jLEstaticoTamanoMuestra1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables



    @Override
    public void actualizarUnObjeto(Object unObjeto) {
        if (unObjeto instanceof Lote){
            asignarObjetoACriterio(0, unObjeto);
            this.unLoteSeleccionado = (Lote) unObjeto;
            exhibirLote();
        }
        if (unObjeto instanceof CriterioAnalisisLaboratorio){
            asignarObjetoACriterio(3, unObjeto);
            this.unCriterioSeleccionado = (CriterioAnalisisLaboratorio) unObjeto;
            exhibirCriterio();
        }
        if (unObjeto instanceof OrdenDeProduccion){
            asignarObjetoACriterio(6, unObjeto);
            this.unaOrdenDeProduccion = (OrdenDeProduccion) unObjeto;
            exhibirOrdenDeProduccion();
        }
        if (unObjeto instanceof Equipamiento){
            asignarObjetoACriterio(7, unObjeto);
            this.unLaboratorio = (Equipamiento) unObjeto;
            exhibirLaboratorio();
        }
        if (unObjeto instanceof OrdenDeCompra){
            asignarObjetoACriterio(8, unObjeto);
            this.unaOrdenDeCompra = (OrdenDeCompra) unObjeto;
            exhibirOrdenDeCompra();
        }
    }

    private void generarBarra() {
    }

    private void configurarOpcionesCensables() {
        datoCriterio4.addItem(AnalisisLaboratorio.ATRIBUTO_PORCENTAJE_HOJA);
        datoCriterio4.addItem(AnalisisLaboratorio.ATRIBUTO_PORCENTAJE_SEMILLA);
        datoCriterio4.addItem(AnalisisLaboratorio.ATRIBUTO_PORCENTAJE_PALO);
        datoCriterio4.addItem(AnalisisLaboratorio.ATRIBUTO_PORCENTAJE_POLVO);
        datoCriterio4.addItem(AnalisisLaboratorio.ATRIBUTO_PORCENTAJE_HUMEDAD);
        
        /*datoCriterio4.addItem(AnalisisLaboratorio.ATRIBUTO_PUNTOS_NEGROS);
        datoCriterio4.addItem(AnalisisLaboratorio.ATRIBUTO_TORRADA);
        datoCriterio4.addItem(AnalisisLaboratorio.ATRIBUTO_COLOR);
        datoCriterio4.addItem(AnalisisLaboratorio.ATRIBUTO_AROMA);
        datoCriterio4.addItem(AnalisisLaboratorio.ATRIBUTO_TACTO);
        */
        
        
        datoCriterio4.setVisible(true);
    }
    
    private void exhibirLote() {
        jLCriterio1.setText("ID "+unLoteSeleccionado.getId()+", etiqueta: "+unLoteSeleccionado.getEtiqueta());
    }

    private void exhibirCriterio() {
        jLCriterio4.setText(unCriterioSeleccionado.getNombre());
    }

    private void exhibirOrdenDeProduccion() {
        jLCriterio7.setText(""+this.unaOrdenDeProduccion.getId());
    }

    private void exhibirLaboratorio() {
        jLCriterio8.setText(unLaboratorio.getNombre());
    }

    private void exhibirOrdenDeCompra() {
        if (unaOrdenDeCompra == null)
            return;
        jLCriterio9.setText(""+unaOrdenDeCompra.getId());
    }

    private void generarBarras(ArrayList listaObservada) throws ExcepcionCargaParametros {
        
        if (listaObservada == null || listaObservada.isEmpty())
            throw new ExcepcionCargaParametros("No existen análisis de laboratorio con los criterios ingresados.");
        
        jPanel6.removeAll();
        Iterator analisis = listaObservada.iterator();
        Object[][] cantidadVecesSubAtributosAvistados = new Object[AnalisisLaboratorio.ATRIBUTOS.length][];
        while (analisis.hasNext()){
            AnalisisLaboratorio unAnalisis = (AnalisisLaboratorio) analisis.next();
            for (int i = 0; i < AnalisisLaboratorio.ATRIBUTOS.length; i++){
                String unAtributo = AnalisisLaboratorio.ATRIBUTOS[i];
                for (int j = 0; j < AnalisisLaboratorio.SUB_ATRIBUTOS[i].length; j++){
                    String unSubAtributo = AnalisisLaboratorio.SUB_ATRIBUTOS[i][j];
                    if (cantidadVecesSubAtributosAvistados[i] == null)
                        cantidadVecesSubAtributosAvistados[i] = new Float[AnalisisLaboratorio.SUB_ATRIBUTOS[i].length];
                    if (cantidadVecesSubAtributosAvistados[i][j] == null)
                        cantidadVecesSubAtributosAvistados[i][j] = 0f;
                    cantidadVecesSubAtributosAvistados[i][j] = (Float)cantidadVecesSubAtributosAvistados[i][j] + unAnalisis.getValorUnAtributo(unAtributo, unSubAtributo);
                }
            }
        }
        for (int i = 0; i < AnalisisLaboratorio.ATRIBUTOS.length; i++){
            String unAtributo = AnalisisLaboratorio.ATRIBUTOS[i];
            ChartPanel unGrafico = Estadistica.generarGraficoBarras(unAtributo, "Categoría", "Frecuencia observada", (Float[]) cantidadVecesSubAtributosAvistados[i], AnalisisLaboratorio.SUB_ATRIBUTOS[i], 0.75f);
            agregarPanelAtributoCualitativo(AnalisisLaboratorio.ATRIBUTOS[i], unGrafico);
        }
//        Estadistica.agregarChartPanel(jPanel4, Estadistica.generarGraficoBarras("Distribucion de variables cualitativas de análisis", "Categorias","Frecuencia",datosObservados, atributos, subAtributos, 1.5f));
        
        
    }
    
    
    private void agregarPanelAtributoCualitativo(String unAtributoCualitativo, ChartPanel unPanelJFreeChart){
        
        JLabel unaEtiqueta = new javax.swing.JLabel();;
        unaEtiqueta.setFont(new java.awt.Font("Dialog", 0, 24)); 
        unaEtiqueta.setText("Distribución de frecuencia observada de "+unAtributoCualitativo);
        jPanel6.add(unaEtiqueta);
        jPanel6.add(Box.createRigidArea(new Dimension(0,5)));
        JPanel unPanel = new JPanel();
        unPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        //javax.swing.GroupLayout unPanelLayout = new javax.swing.GroupLayout(unPanel);
        
        Estadistica.agregarChartPanel(unPanel, unPanelJFreeChart);
        jPanel6.add(unPanel);
        jPanel6.add(Box.createRigidArea(new Dimension(0,5)));
        unPanel.setVisible(true);
    }

    private void generarTortaAprobadosYDesaprobados(ArrayList listaObservada) throws ExcepcionCargaParametros {
        if (listaObservada == null || listaObservada.isEmpty())
            throw new ExcepcionCargaParametros("No existen análisis de laboratorio con los criterios ingresados.");
        jPanel4.removeAll();
        Map <String, Float> partes = new HashMap<String, Float>();
        Float cantidadDeAprobados = 0f;
        Float cantidadDeRechazados = 0f;
        Iterator analisis = listaObservada.iterator();
        while (analisis.hasNext()){
            AnalisisLaboratorio unAnalisis = (AnalisisLaboratorio) analisis.next();
            if (unAnalisis.estaAprobado())
                cantidadDeAprobados++;
            else
                cantidadDeRechazados++;
        }
        partes.put("Aprobados", cantidadDeAprobados);
        partes.put("Rechazados", cantidadDeRechazados);
        ChartPanel unChartPanel = Estadistica.generarPanelGraficoTortaFlotante(partes, "Conclusiones totales de la lista filtrada", 0.75f, "análisis");
        Estadistica.agregarChartPanel(jPanel4, unChartPanel);
    }
}
